### ISSUE TITLE
What are "types"

### ISSUE THREAD

**Issue by bhousel** [osmlab/osm-community-index#1]
Each resource has a `"type"` property.. 

```js
{
    "type": "Feature",
    "properties": {
        "id": "OSM-US-Slack",
        "type": "slack",
        "country_code": "US",
        "name": "OpenStreetMap US Slack",
        "description": "Sign up at {url}",
        "url": "https://osmus-slack.herokuapp.com/"
    },
    "geometry": { 
        ...
    }
```

I left this a free-text property.  But we might want to have a list of acceptable types.

**Comment by althio** [comment]
Which icons would fit for forums and mailing lists?

**Comment by bhousel** [comment]
> Which icons would fit for forums and mailing lists?

Good point @althio ... Maybe we should just define a list of accepted types to avoid any confusion.  We can easily expand the list later.

As for the icons, there are about 1000 free (CC BY 4.0) icons to pick from (the brands are a subset):   https://fontawesome.com/icons?d=gallery&m=free

**Comment by bhousel** [comment]
The list of allowable types is:
```
            "enum": [
                "facebook",
                "forum",
                "mailinglist",
                "meetup",
                "reddit",
                "slack",
                "telegram",
                "twitter",
                "website"
            ]
```

Let me know if we're missing anything

**Comment by joostschouppe** [comment]
The list of types has grown quite a bit. The map-filter @jbelien made (at https://community.osm.be/) makes this very visible. How about these two: 

"osm" - a local OpenStreetMap page
"group" - A site for a local group with a url (such as a local OSM chapter page)

When I look at what's behind those two, they are basically the same. Everything under there could as well be "website". The only two exceptions, are "meetup groups organizing on the wiki" classified as a "group". I would propose changing those to "wiki", reclassify all others to "website".

I would also propose to add a new thing: lc-website. This would be for websites for organisations that are an officially recognized Local Chapter.

**Comment by bhousel** [comment]
> "osm" - a local OpenStreetMap page
> "group" - A site for a local group with a url (such as a local OSM chapter page)
> 
> When I look at what's behind those two, they are basically the same. Everything under there could as well be "website". The only two exceptions, are "meetup groups organizing on the wiki" classified as a "group". I would propose changing those to "wiki", reclassify all others to "website".

Good points.. I still think of "types" as mostly "what icon to pick".  

We should definitely change the description for `group` to not suggest that it is a local OSM chapter page.  I think of "groups" more things like Maptime, or Mappa Merica, or Map Kibera - things where it would be misleading and weird to show an OSM logo next to them.

I'm ok with adding a new type for officially recognized local chapter pages.  We could have `osm-lc` and `osm` to differentiate between official and unofficial local OSM groups.

**Comment by bhousel** [comment]
@joostschouppe I did a few things!

* I updated the [contributing guidelines](https://github.com/osmlab/osm-community-index/blob/master/CONTRIBUTING.md) to improve the descriptions of the types, and show icons too.  It looks nice!
* I added a special `osm-lc` type and icon for official local chapters.  The icon is like the OSM icon, but it has a star ⭐️  
* I updated the groups and local chapters in this index, and added whatever other official local chapters I could find [here](https://wiki.openstreetmap.org/wiki/Foundation/Local_Chapters)

**Comment by jbelien** [comment]
Awesome!
Thanks a lot @bhousel ! I'll integrate this in https://community.osm.be/ in the next few days 🎉

**Comment by simonpoole** [comment]
@bhousel the actual list of local chapters is here  https://wiki.osmfoundation.org/wiki/Local_Chapters

**Comment by bhousel** [comment]
> the actual list of local chapters is here https://wiki.osmfoundation.org/wiki/Local_Chapters

ok, I just checked and thankfully it is the same list.
(Belgium, France, Germany, Iceland, Ireland, Italy, Switzerland, United Kingdom)
