### ISSUE TITLE
Add Japanese Community 🇯🇵

### ISSUE THREAD

**Issue by nyampire** [osmlab/osm-community-index#10]
Here are contact points for Japanese Community.

* talk-ja: https://lists.openstreetmap.org/listinfo/talk-ja
* Twitter: #osmjp
* Facebook: https://www.facebook.com/groups/osmjapan/

**Comment by bhousel** [comment]
Update:  the [CONTRIBUTING.md](https://github.com/osmlab/osm-community-index/blob/master/CONTRIBUTING.md) guide is done and the doc schemas are stable now. 

See https://github.com/osmlab/osm-community-index/issues/27#issuecomment-377539650 for how to add the resources to the index.

**Comment by nyampire** [comment]
@bhousel Thank you. I'm working on adding those resources.
I'm a bit wondering about features geojson. Currently I'm including the area which Japanese government claims (means "including disputed area")

https://github.com/nyampire/osm-community-index/blob/japan_spike/features/asia/japan/japan.geojson

Is it better to fix to suite "on the ground" OSM(F) rule?

**Comment by bhousel** [comment]
> I'm a bit wondering about features geojson. Currently I'm including the area which Japanese government claims (means "including disputed area")

This polygon will be used to show a user who edits in this area that there is a community nearby that they can join.  It's ok for the polygon to be very rough, and in fact fewer points is better because it will enable faster lookups and take up less space..

**Comment by bhousel** [comment]
For example, I chopped the whole top of Russia, because that coastline detail just doesn't matter for what we're using it for (test is the user editing anywhere in here or not)
https://github.com/osmlab/osm-community-index/blob/master/features/asia/russia/russia.geojson

**Comment by nyampire** [comment]
Thanks. I've pushed my commit as #40.
