### ISSUE TITLE
Highlight FIXME-Tags?

### ISSUE THREAD

**Issue by mathesoft** [osmlab/osm-community-index#101]
Hey,

is there any way (or planned to implement) to highlight all FIXME-Tags while use the iD-Editor to make the map better?
Or maybe a button to generate a list of these tags of actual editing view (+10km around).

With the 'search object' function it is not possible to find...

**Comment by bhousel** [comment]
The best thing I can suggest is to use a dedicated QA tool like [Keepright](http://osm.mueschelsoft.de/keepright) to find them.
Adding that as a layer in iD is tracked here: https://github.com/openstreetmap/iD/issues/3452

(btw, this repository is for the community links only, not general iD issues)
