### ISSUE TITLE
Community map websites as resources

### ISSUE THREAD

**Issue by SK53** [osmlab/osm-community-index#108]
Can I ask for an additional resource type of map website. I am thinking in particular of site such as these:

- Mapio cymru, a welsh-language render of OSM data: https://openstreetmap.cymru/
-  OpenStreetMap e brezhoneg, a breton render of OSM data https://kartenn.openstreetmap.bzh/#map=8/48.1/-2.3 (part of a broader website which could be handled as a group resource)
- OSM-Nottingham: a site dedicated to showing OSM data and enabling search of open data for mapping purposes run by a member of the East Midlands OSM community (and thus distinctly not a group, but a highly valuable resource for mappers in the area): http://osm-nottingham.org.uk/
- Evesham Mapped: as above and run by the same person although originally established for his late father, also a keen mapper. http://www.evesham-mapped.org.uk/
- OSM Ireland have several useful map pages: Old Maps, boundaries and an Irish language render.

@SomeoneElse also has his "Useful Maps" site which covers Britain & Ireland and is often a much better reference than the main site, but I would need to check with him about marking it as a publicly available resource, whereas the others were designed as such from the outset.

Where the site is of a group, having a separate map resource may be unnecessary, but for map-only sites and minority languages I think these are important pointers for contributors as these sites may provide the reinforcement to see that their edits are useful and being consumed. Obviously there may need to be some other ground rules: that the map is clearly built for & maintained by part of the community. Edge cases may be things like the University of Cambridge map created with as part of a commercial contract, but really useful to understand the basis of a lot of mapping in the city.

I'm slightly surprised that I'm not aware of other local OSM maps along the lines of those by Will Philips (OSM Nottingham & Evesham Mapped). Such a site is always more likely to have useful content for local people & the OSM community, without imposing the need to generate additional content that always exists for a user group site.

**Comment by bhousel** [comment]
Thanks for the suggestion - but this index is really more for social resources.  The goal here is to have users (especially those brand new) realize that they are part of a larger community, but also to see that there are people around them who care about the map.

[This paper](https://www.tandfonline.com/doi/full/10.1080/13658816.2018.1458312) that was just released recently does a great job analyzing the lifecycle of a contributor to an open project like OSM. (I did not know about the paper when building this index or adding the feature to iD).  

But the idea is that users go through phases of **assessment** (deciding "is this project right for me") **engagement** (active participation) and **detachment** (leaving the project).  We have a very limited window of opportunity to move users from "assessment" to "engagement", and obviously we want to keep people out of the "detachment" phase.

_This index is for users in the assessment phase._ 

You'll see me push back on suggestions to add the kinds of resources that engaged users want to see (osm wiki, mailing lists, or places where people gather to talk about what tags are the right ones).  

By the way - a good idea would be to design 3 different "you just saved your edit" screens for the three different kinds of users.  Users who are already engaged might want to see links to the wiki, mailing lists, documentation about how to tag.

**Comment by bhousel** [comment]
Alternatively - another thing we could do would be to just add _everything_ to this index, but also add properties to describe which resources are social or beginner-friendly.

**Comment by SK53** [comment]
The two Breton & Welsh language sites are precisely at the assessment phase.

In general I am advocating such links for people in the assessment phase as they demonstrate aspects of OSM which are not surfaced on the main site, or even on country-specific sites. You only have to look at recent edits featuring name:cy to see this for the Welsh map and the wealth of comments generated by the publicity associated with the creation of the map. A failure to link to resources which show that, for instance, welsh-language names are visible will inevitably weaken our ability to reach the relatively small community who can improve OSM in this area. The alternative of going through the whole process of "OSM is mainly a database not a map" largely works for those who are already engaged, and probably works best for those with an IT/STEM background.

I think, by the way, that there are many users who are engaged with mapping but who are not necessarily aware of the full plethora of resources available, and the index may give them more incentive to extend their interaction. OTOH, I think Frederik Ramm pointed out some years ago that the majority of mappers do not interact at all.
