### ISSUE TITLE
Contacts for Russian community

### ISSUE THREAD

**Issue by Zverik** [osmlab/osm-community-index#11]
We have two main points of entry:

* Forum: https://forum.openstreetmap.org/viewforum.php?id=21
* Telegram: https://t.me/ruosm

And a few secondary channels: IRC, Vkontakte, OSM Diaries.

(I'd add these myself, but I have no idea how this repository is structured and what is needed)

**Comment by bhousel** [comment]
Thanks @Zverik  - the [CONTRIBUTING.md](https://github.com/osmlab/osm-community-index/blob/master/CONTRIBUTING.md) guide is done and the doc schemas are stable now. 

See https://github.com/osmlab/osm-community-index/issues/27#issuecomment-377539650 for how to add the resources to the index.
