### ISSUE TITLE
Allow for ordering of communication channels

### ISSUE THREAD

**Issue by joostschouppe** [osmlab/osm-community-index#114]
I'm not sure what the logic to ordering the channels is in the ID user interface right now, but I would prefer it his could be controlled by the local community. In the case of Belgium, the Facebook group is on top, but that's really the least lively channel we offer. With imagery, we have a "best imagery source" thing; maybe we could mark one of the channels as "most active for this area" and show that on top.
(I would understand if we want to keep this out of scope, because it opens the door to so many discussions. Having them show randomized would be good too I think.)

**Comment by bhousel** [comment]
Oh good suggestion @joostschouppe and definitely in scope.  I wanted to open this as an issue and forgot to.

Agree we should add a `sort` parameter or some way to let local communities control the order.

For comparison the current code in iD just hardcodes some numbers (so I could ship something quickly) and I would love to get rid of it:
```js
    // All else being equal, rank more "social" communities higher
    // (anything not in this list receives no adjustment)
    var COMMUNITYRANK = {
        'meetup': +5,
        'slack': +4,
        'facebook': +3,
        'reddit': +2,
        'forum': -2,
        'mailinglist': -3,
        'irc': -4
    };
```

**Comment by govvin** [comment]
Has this been implemented? How does it work?

**Comment by bhousel** [comment]
> Has this been implemented? How does it work?

Nothing implemented yet..

**Comment by mmd-osm** [comment]
Weighted shuffling could be used to stop people from complaining about an unfair treatment which always lists some channels first. More randomness is fun as you might discover new stuff over time (assuming a user won’t read the entire list anyway)

https://www.npmjs.com/package/weighted-shuffle

**Comment by andrewharvey** [comment]
> Weighted shuffling 

I think a fixed predictable sorting which can be customised for each region is best. In my opinion the channels with the most engagement would be at the top, and the less frequently used ones at the bottom, so we help direct people to where there is more activity and hence best likely to get help.

**Comment by Komzpa** [comment]
Can this be resolved by having something like `reach_estimate` with some number of people reachable via this channel?

**Comment by bhousel** [comment]
I was thinking we would just add a generic sounding field like `order` so local communities can order the entries according to whatever criteria they want to use.

**Comment by Komzpa** [comment]
This will not work well - you can do that arbitrarily within one shape, but for two overlapping ones you have to provide a common criteria. Same holds for global communities: are they above (as there are more people) or below (as they are less specific) local ones?

**Comment by bhousel** [comment]
>  you can do that arbitrarily within one shape, but for two overlapping ones you have to provide a common criteria. Same holds for global communities: are they above (as there are more people) or below (as they are less specific) local ones?

**Comment by joostschouppe** [comment]
reach_estimate might not be the best measure. For example, a chat room might be only 20 people, but where all the conversation is happening. While the mailing list might have 200 members but have only one message every other month or two. I think the community-filled 'order' is probably best. And indeed, starting with the most local channels first.
