### ISSUE TITLE
Are supra-national channels welcome?

### ISSUE THREAD

**Issue by joostschouppe** [osmlab/osm-community-index#129]
When adding some Telegram channels, I was reminded of the LatAm telegram channel. It is very relevant to Latin Americans, but then again it's not local and if we start adding supranational channels too, the result might be overwhelming.

**Comment by bhousel** [comment]
Yes!  They are welcome :)   I agree we don't want to overwhelm, but I am guessing that there can't be very many of these.  Adding one or two supra-national items to the list should be fine, especially if they are relevant. (iD will sort the most local items first).

**Comment by joostschouppe** [comment]
OK, great. Where to put them though? The LatAm group is already problematic, since it belongs in both North and South America.

**Comment by bhousel** [comment]
done in #171, #172, thanks @joostschouppe 👍
