### ISSUE TITLE
Switch IRC urls from irc2go.com / irc.openstreetmap.org -> webchat.oftc.net

### ISSUE THREAD

**Issue by harry-wood** [osmlab/osm-community-index#136]
We have some links to irc2go.com. D'you think we should link irc.openstreetmap.org instead?

There's a URL trick for doing this. The `chan` parameter sets that form value. So for example instead of http://en.irc2go.com/webchat/?net=OFTC&room=osm-gb we'd link https://irc.openstreetmap.org/?chan=osm-gb

I _think_ it would be better for a couple of reasons. 1) I suppose being on a "openstreetmap.org" domain looks more professional/reassuring.  2) irc2go (links like this http://en.irc2go.com/webchat/?net=OFTC&room=osm-gb ) tries to launch a java applet, and who uses java applets these days? (I seem to have managed to browse the web for four months on a new laptop without ever needing to, so this link basically doesn't work for me unless I do some horrible set-up process)

**Comment by bhousel** [comment]
Sure, switching to irc.openstreetmap.org seems ok.

**Comment by harry-wood** [comment]
I was noticing today that the `chan` parameter doesn't actually work. It _looks_ like it's working (so much so that we didn't notice the problem) bit it goes on to connect you to the default #osm channel. 

Seems like a bug in cgiirc which I've reported here: https://github.com/dgl/cgiirc/issues/12

**Comment by FredrikLindseth** [comment]
Can't you just use https://webchat.oftc.net/?channels=osm-gb instead? Works fine

**Comment by harry-wood** [comment]
Lack of response upstream from the cgiirc developers, so that's annoying. I think we should fork the landing page form and make it more OpenStreetMap-styled anyway, so that could be the ultimate solution.

In the meantime @FredrikLindseth 's suggestion seems good. There's something nice and "native" about linking to the people that actually host the IRC channels, and they have a webchat interface with *working* channel links! That's cool. Didn't know about it.

**Comment by bhousel** [comment]
Tagged this is a good first issue for anyone who wants to contribute.  Task here would be to replace any current `irc2go.com` or `irc.openstreetmap.org` links with `webchat.oftc.net` links.

**Comment by techac** [comment]
can I work on this issue. As I am new to this project can you please specifically tell exactly what part of codebase should I work on?
Thanks..

**Comment by harry-wood** [comment]
Welcome! Look at the JSON data files under 'resources'.  It's going to look quite similar to this commit: https://github.com/osmlab/osm-community-index/commit/366f9a63a4d892747e22b2a33655cf4cece5c40e  but changing the URLs again.
