### ISSUE TITLE
YouthMappers

### ISSUE THREAD

**Issue by bhousel** [osmlab/osm-community-index#152]
Followup from discussion at OSM US Hackathon
Let's add YouthMappers chapters to this index!
cc @Geocruizer

**Comment by bhousel** [comment]
Hey @geocruizer just bumping this task - do you have a list of YouthMappers chapters?  

Maybe we can coordinate in a Google doc or something?  I can help get this all set up with instructions and generate some bounding boxes around each chapter.

It would be really super to task this out to Hacktoberfest volunteers over the month of October. 😎

**Comment by Geocruizer** [comment]
Hey Bryan,

Thanks for reaching out and keeping me honest on promises.  Attached is the
.csv for current YM chapters.  Happy to clean up the spreadsheet to make it
easier for you.  There is a photo hosted on dropbox which is probably
useless for this purpose. ContactURL is the chapters email which might be
good to post, and there is a link to the FB page for those who have it.

Let me know what you think works best.

Thanks,
Chad

**Comment by bhousel** [comment]
> Thanks for reaching out and keeping me honest on promises. Attached is the .csv for current YM chapters. Happy to clean up the spreadsheet to make it easier for you. There is a photo hosted on dropbox which is probably useless for this purpose. ContactURL is the chapters email which might be good to post, and there is a link to the FB page for those who have it.

Thanks @Geocruizer - the attachment didn't make it through GitHub.. 
Can you instead email me directly at bryan@mapbox.com

**Comment by bhousel** [comment]
Cc @quincylvania
