### ISSUE TITLE
What is a 'local' user?

### ISSUE THREAD

**Issue by mvexel** [osmlab/osm-community-index#16]
Trying to understand the scope. Everyone using OSM is a 'local' user. Is this supposed to explicitly exclude "global" resources like the OSM wiki, global mailing lists etc?

Happy to work on the README as this becomes clearer to me.

**Comment by bhousel** [comment]
Thanks @mvexel - I'm trying to figure this out too.

We should probably remove "local" from the descriptions, however the preference should still be towards exposing new mappers to local resources ahead of regional or global ones.

This project was inspired by https://github.com/openstreetmap/iD/issues/4815 and so the initial scope is "build a thing that makes that even possible".

Here's a rough mockup of what I'm thinking of:

<img width="712" alt="screenshot 2018-03-13 12 57 45" src="https://user-images.githubusercontent.com/38784/37357256-4fa8238e-26be-11e8-9e77-2da923eacea0.png">

**Comment by bhousel** [comment]
Also worth mentioning that this is not _just_ an iD feature.  It has broader appeal and we're thinking of adding something like to other OSM tech.

For example, even if you are armchair mapping somewhere not local to you, it might be useful to reach out to someone local to address an issue. Like if you are reviewing stuff in OSMCha and see something fishy, and want to send off a message to someone like "Hey I noticed something in Fairfax VA that looks like vandalism, but I'm not sure - want to take a look?"

**Comment by mvexel** [comment]
Cool. I made [a halfhearted attempt at this](https://github.com/osmlab/localgroups) some years ago, and am glad that someone is willing to put some more weight behind the idea. Bravo! Some of the info in there may still be relevant, feel free to pilfer.

Defining 'local' may be irrelevant as long as folks users of this list can apply some filtering on geographical scope and things like in-person vs online, medium (email, web, ..), proprietary or open. Sans that, it might be tough to use.

**Comment by bhousel** [comment]
> Cool. I made a halfhearted attempt at this some years ago, and am glad that someone is willing to put some more weight behind the idea. Bravo! Some of the info in there may still be relevant, feel free to pilfer.

That is great, thanks..  I feel bad that I didn't know about the earlier effort - sorry!

**Comment by 1ec5** [comment]
For what it’s worth, there’s also [osmus/local-wg](https://github.com/osmus/local-wg/), which includes various U.S. local groups as well.
