### ISSUE TITLE
Join Mastodon – Mastodon is missing

### ISSUE THREAD

**Issue by rugk** [osmlab/osm-community-index#166]
## Community Resource Name

OpenStreetMap on Mastodon

### What is it?

[Mastodon](https://joinmastodon.org/) ( a decentralized Twitter alternative)

### URL link to the resource

https://en.osm.town/@openstreetmap

Only a mirror though…

So you may join there!

### Points of contact

no idea

### Bounding polygon
??

### Languages spoken (optional)

same as Twitter, I suppose

**Comment by bhousel** [comment]
Nah, it's just a mirror of @openstreetmap on Twitter.

**Comment by rugk** [comment]
Sure, so set up a real Madison account!

**Comment by tuxayo** [comment]
> Nah, it's just a mirror of @ openstreetmap on Twitter.

Then it allows people to follow @ openstreetmap without having to accept the terms of use[1] of Twitter. Or other controversial attributes of the platform. Like it's business model.

That how more respectable social networks will develop, by being mirrors.
And if it takes the place of the previous one. Then the previous one will be a mirror. 

Can this be reopened? At least in mode "well written patches will be accepted"

[1] https://tosdr.org/#twitter
