### ISSUE TITLE
Official IRC Channel 

### ISSUE THREAD

**Issue by 301-freq** [osmlab/osm-community-index#177]
Quite simply, a room has formed as the Official Open Street Map Congregation point on IRC. It is: irc.oftc.net #openstreetmap

Quick link: https://webchat.oftc.net/?channels=openstreetmap

Please come join us in idea forming and technical support!

**Comment by iandees** [comment]
Do you mean #osm (as referenced in the wiki at https://wiki.openstreetmap.org/wiki/IRC)?

**Comment by 301-freq** [comment]
I was not aware of this. I thought there was no channel made yet. Thanks!
