### ISSUE TITLE
OSM Latam is global?

### ISSUE THREAD

**Issue by andrewharvey** [osmlab/osm-community-index#179]
When I edit in iD in Australia I see a suggestion for OSM Latam, which I wouldn't expect to show up here.

![selection_999 052](https://user-images.githubusercontent.com/117278/44855982-9e4e8380-acaf-11e8-91ea-c880e138331e.png)

**Comment by Notoncebut2x** [comment]
Noticed the same issue while mapping in Nigeria...is it because SOTM Latam is coming up?
![capture](https://user-images.githubusercontent.com/4581716/44861364-5ba49100-ac46-11e8-82c4-f56ef7d4764f.PNG)

**Comment by manfredbrandl** [comment]
I noticed the same while editing near Atlas Bouy (0.00 E 0.00 N) , see https://github.com/openstreetmap/iD/issues/5282

**Comment by bhousel** [comment]
fixed in 3bdc531
