### ISSUE TITLE
OSM India  : Telegram and Youtube link.

### ISSUE THREAD

**Issue by naveenpf** [osmlab/osm-community-index#198]
OSM IN
Telegram link
https://t.me/OSMIndia

Youtube channel 

https://www.youtube.com/channel/UCu5sKaPU04x0RJkgGkoFORw

**Comment by naveenpf** [comment]
OSM India website is missing
https://openstreetmap.in

**Comment by naveenpf** [comment]
Forum and wiki too missing

Can we add github always ?

https://wiki.openstreetmap.org/wiki/WikiProject_India/Maintainers

@jinalfoflia

**Comment by jinalfoflia** [comment]
Thank you @naveenpf for bringing all of this together. Do you want me to add this to community-index?

**Comment by naveenpf** [comment]
yes please

**Comment by naveenpf** [comment]
@planemad  done #199

**Comment by bhousel** [comment]
Just merged, thank you @naveenpf!  👍
