### ISSUE TITLE
Let's talk about `description`

### ISSUE THREAD

**Issue by bhousel** [osmlab/osm-community-index#20]
The example community resource has this:

```js
{
  "id": "OSM-US-Slack",
  "name": "OpenStreetMap US Slack",
  "description": "Sign up at {url}",
  "url": "https://osmus-slack.herokuapp.com/",
  ...
}
```

That description is not great.  It's really just a placeholder.
Using my iD mockup below for inspiration - what kinds of things do we want to include in a description?

* How long is reasonable?  A few lines? 
* Formatting?  We could do markdown, but I'd rather not.
* I put that `{url}` token in there, thinking we might replace it with the real url, but then we also need url text.  Thinking about it more, I'd prefer not to do token replacements unless we have a compelling reason.
* That `url` link goes to the auto-inviter, not to the actual url which is https://osmus.slack.com - is that weird?  (maybe need separate signup and visit links?)
* Should we add another field for a more _extended_ description, maybe more suited for an expandable block of text, like these "details" things:
  <details>
      lots of good stuff in here 
  </details>

---

<img width="712" alt="screenshot 2018-03-13 12 57 45" src="https://user-images.githubusercontent.com/38784/37383363-b88439d2-271e-11e8-9b0b-94f2ef2e7aab.png">

**Comment by althio** [comment]
> How long is reasonable? A few lines?
Should we add another field for a more extended description, maybe more suited for an expandable block of text, like these "details" things

I would like a short description (1 line) and a extended description (expandable block)

><< Formatting? We could do markdown, but I'd rather not.

Maybe formatting is overkill for a description. Or keep that for another later issue.

> That url link goes to the auto-inviter, not to the actual url which is https://osmus.slack.com - is that weird? (maybe need separate signup and visit links?)

Yes to separate links signup/visit.
