### ISSUE TITLE
Support new channel types: homepage, github, youtube, wiki

### ISSUE THREAD

**Issue by planemad** [osmlab/osm-community-index#200]
From 
https://github.com/osmlab/osm-community-index/pull/199#issuecomment-443113050

It looks like for India we need new channel types that are not currently supported: 
- `homepage`: For the localized OSM website. Some communities are [using `group` for this](https://github.com/osmlab/osm-community-index/blob/master/resources/asia/japan/OSM-Japan-website.json) but homepage maybe a more clear term. 
- `youtube`
- `wiki`(previously ticketed in 
https://github.com/osmlab/osm-community-index/issues/74#issuecomment-388596622)
- `github`

Any objections to adding this?

cc @naveenpf

**Comment by naveenpf** [comment]
github is not supported ?

**Comment by planemad** [comment]
Possibly because it is not considered a medium primarily for community discussions, just as youtube and the wiki.

Theres value in adding this though as it does make it easier to find all this information in a single place especially for someone new.

**Comment by bhousel** [comment]
Actually thinking about it more, it seems reasonable to leave "group" for local chapters and add "website" for other sites  (as long as we communicate this clearly in the docs)

**Comment by bhousel** [comment]
ok, this was done!  The new complete list of types is now:
  * "discord"
  * "discourse"
  * "facebook"
  * "forum" - For example, on forum.openstreetmap.org
  * "github"
  * "group" - A site for a local group with a `url` (such as a local OSM chapter page)
  * "irc" - `url` should be a clickable web join link, server details can go in `description`
  * "mailinglist" - `url` should be a link to the listinfo page, e.g. `https://lists.openstreetmap.org/listinfo/talk-us`
  * "matrix" - e.g. [Riot Chat](https://matrix.org/docs/projects/client/riot.html)
  * "meetup"
  * "osm" - a local OpenStreetMap page
  * "reddit"
  * "slack" - `url` should link to the Slack itself, and `signupUrl` can link to an inviter service (see example above)
  * "telegram"
  * "twitter"
  * "url" - Generic catchall for anything with a `url`
  * "wiki" - An OpenStreetMap [wiki project page](https://wiki.openstreetmap.org/wiki/List_of_territory_based_projects)
  * "youtube"

also, each type maps to an icon under `dist/img/`
