### ISSUE TITLE
Korea country code (and folder name)

### ISSUE THREAD

**Issue by jbelien** [osmlab/osm-community-index#205]
I noticed while upgrading "[OpenStreetMap Community Index Viewer](https://community.osm.be/)" an issue with Korea.

They used the country code [`KO`](https://www.iso.org/obp/ui/#search/code/ko) which doesn't seem to be a [valid ISO code](https://www.iso.org/obp/ui/#search/code/). It should be [`KR`](https://www.iso.org/obp/ui/#iso:code:3166:KR) for South Korea or [`KP`](https://www.iso.org/obp/ui/#iso:code:3166:KP) for North Korea.

In the same order of idea, I think we should use `asia/south_korea` instead of `asia/korea` for the folder name.

**Comment by jbelien** [comment]
Awesome, thanks a lot @bhousel ! :)

Just a quick notice: https://github.com/osmlab/osm-community-index/blob/master/features/asia/south_korea/south_korea.geojson is whole korea, not just south korea.

**Comment by bhousel** [comment]
> Just a quick notice: https://github.com/osmlab/osm-community-index/blob/master/features/asia/south_korea/south_korea.geojson is whole korea, not just south korea.

Whoops - thanks for catching this! I fixed in 1f2aa15 by splitting them into 2 files.
