### ISSUE TITLE
lacking the discord of the Brazilian community in the OSM

### ISSUE THREAD

**Issue by eduaddad** [osmlab/osm-community-index#214]
add discord server Brazilian community

language: Brazilian Portuguese (pt-br)

https://discord.gg/bQn4aCm

**Comment by quincylvania** [comment]
@eduaddad We can add this, but we need the name and public email address of someone connected to the Discord willing to be a point of contact. ([Example](https://github.com/osmlab/osm-community-index/blob/fa99c8466807a6b55e3d4d8602019763bccac300/resources/south-america/brazil/OSM-br-telegram.json#L11))

**Comment by eduaddad** [comment]
Eduardo Addad de Oliveira
duduaddad@gmail.com
