### ISSUE TITLE
Add Galician community resources

### ISSUE THREAD

**Issue by Ivans-Git** [osmlab/osm-community-index#216]
From the Galician community, we ask that when the map has just been mapped in Galicia, the official Telegram and the Twitter of our community appear.
Telegram: https://t.me/joinchat/AAHZsRBs-mY3hrquk2kpig
Twitter: https://twitter.com/osmgalicia
And Wiki: https://wiki.openstreetmap.org/wiki/Gl:P%C3%A1xina_principal

Thanks for making it possible, greetings from Galiza!

**Comment by joostschouppe** [comment]
There's pull requests for all of this. The data you provided is a little limited. Have a look at what a new Issue suggests for inspiration.

**Comment by bhousel** [comment]
Done in #268.. Thanks @joostschouppe  👏
