### ISSUE TITLE
Add talk-us mailing list to the USA entry

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/osm-community-index#218]
## Community Resource Name

"OpenStreetMap US Mailing List"

### What is it?

mailing list

### URL link to the resource

https://lists.openstreetmap.org/listinfo/talk-us

### Points of contact

no idea

### Bounding polygon

not needed, just add it to https://github.com/osmlab/osm-community-index/blob/master/resources/north-america/united_states/OSM-US.json

### Languages spoken (optional)

"en"

### Country codes (optional)

"us"

### Add an emoji flag (optional)

no emoji, please

**Comment by bhousel** [comment]
See #219
