### ISSUE TITLE
Conflate from list of Telegram channels on the wiki

### ISSUE THREAD

**Issue by mikelmaron** [osmlab/osm-community-index#220]
Huge list! https://wiki.openstreetmap.org/wiki/List_of_OSM_centric_Telegram_accounts

Not sure how active each are.

Wonder how many are already captured in the community-index, and how many active ones are missing?

Would be great to eventually see a canonical listing here in osm-community-index.

(This is an idea I want to float, and understand it's a big chunk of work and not necessarily immediately actionable).

**Comment by bhousel** [comment]
I went through the Telegram list and it looks like the community index has most of them.. 

I'll add the remaining ones in the next day or so.  I'll skip the ones that mostly look like bot accounts or just translations of the OSM blog.  Also there are a lot of Brazilian ones where I'm not sure we need each city to have one, so I'll skip those too. 

Your map has been really helpful!  There are some notable blank spots in the Balkans and Middle East.

**Comment by Bibi56** [comment]
The issue are not IMHO the blank spots but the opposite: promoting Telegram groups that have no relation to the community.
I'm thinking about France: nobody from the local chapter OpenStreetMap France seems to have ever heard about that group.

**Comment by brandoncote** [comment]
Please add the OSM Canada telegram group

**Comment by bhousel** [comment]
> Please add the OSM Canada telegram group

Just added in 07fdb43, thanks!

**Comment by bhousel** [comment]
> The issue are not IMHO the blank spots but the opposite: promoting Telegram groups that have no relation to the community.
> I'm thinking about France: nobody from the local chapter OpenStreetMap France seems to have ever heard about that group.

Hey @Bibi56 , I'm just catching up to this now.. 
If you see anything in the index that your community doesn't want promoted, please let me know and I'm happy to remove it.  Also you can just change the wiki page of telegram accounts linked above.
