### ISSUE TITLE
Iranian Social Network

### ISSUE THREAD

**Issue by MakarehCo** [osmlab/osm-community-index#222]
## Community Resource Name

Please Create an account in iranian social network "SORUSH"

https://sapp.ir

**Comment by quincylvania** [comment]
Hi @MakarehCo, this project is for promoting existing community resources, not creating new ones. Maybe the OSM in Iran [wiki page](https://wiki.openstreetmap.org/wiki/WikiProject_Iran) would be helpful to you?

If you or someone else creates this resource then we can consider adding it to this index!
