### ISSUE TITLE
Integrate User groups in Wiki via UserGroupsBot 

### ISSUE THREAD

**Issue by mmd-osm** [osmlab/osm-community-index#23]
See wiki page: https://wiki.openstreetmap.org/wiki/User:UserGroupsBot

A bot automatically creates a [kml resource](https://github.com/fossgis/openstreetmap.de/blob/master/map_src/osm_user_groups_dach.kml) based on User Groups maintained on the Wiki. Essentially this means that everyone is free to add local user group meetings in the Wiki without creating some pull request here.

Results are shown e.g. on different specialized maps, such as https://www.openstreetmap.de/karte.html, see the small icons on the "Lokale Gruppen" (local group) overlay.

Edit: ah, something similar was already discussed before in another repo: https://github.com/osmlab/osm-planning/issues/5#issuecomment-371404986. Everyone maintaining their own list is probably creating extra effort, so leveraging  what is already available as much as possible would be a plus.

BTW:  https://xkcd.com/927/ anyone? :sunglasses:

**Comment by Nakaner** [comment]
The Usergroups-Bot collects user groups worldwide but openstreetmap.de shows only the German part. All groups can be seen at http://usergroups.openstreetmap.de/

The source code of the bot can be found at https://github.com/fossgis/usergroups-bot.

**Comment by bhousel** [comment]
Yes, there are other lists of local user groups out there, but the reason I created this project is because I really need a bounding geometry assigned to each group so I can limit the group list to where the group is actually active and relevant.  AFAIK, the wiki doesn't provide this, and it's just a list with each entry having a single coordinate.  (see #16 for more info about why this project exists).

A bot to connect this index and other group lists would be a great idea, but I'd like to leave it as out of scope for this project for now while we are just getting started.

**Comment by mmd-osm** [comment]
>  I really need a bounding geometry assigned to each group so I can limit the group list to where the group is actually active and relevant. 

Yes, that's a fair point. Maybe we could extend the Wiki template accordingly, e.g. by providing a radius along with the lat/lon value, or maybe some reference to existing OSM geometry. Do you have some more specific requirements to take into account? Would you be willing to revisit this topic if additional data would be available?

> A bot to connect this index and other group lists would be a great idea, but I'd like to leave it as out of scope for this project for now while we are just getting started.

A closed issue gets easily overlooked, after all. Where should this be tracked then?

**Comment by bhousel** [comment]
> Would you be willing to revisit this topic if additional data would be available?

Of course!

> A closed issue gets easily overlooked, after all. Where should this be tracked then?

At least in my mind, closed just means "not now".   I still get email notifications when people discuss on closed issues, and if this is something that keeps being an issue months from now, we can reopen it.

**Comment by mikelmaron** [comment]
What do you think about taking another look at this @bhousel, now that the index handles points (ala YouthMappers groups). UserGroups now creates [GeoJSON ](https://usergroups.openstreetmap.de/osm_user_groups.json) too

**Comment by bhousel** [comment]
> What do you think about taking another look at this @bhousel, now that the index handles points (ala YouthMappers groups). UserGroups now creates [GeoJSON ](https://usergroups.openstreetmap.de/osm_user_groups.json) too

We could do a one-time import, but I don't have the bandwidth to write tools to keep the two lists in sync.
