### ISSUE TITLE
add talk-ch

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/osm-community-index#231]
mentioned at https://wiki.openstreetmap.org/wiki/WikiProject_Switzerland as one of two main communication channels, appears to be far more active than https://forum.openstreetmap.org/viewforum.php?id=30

## Community Resource Name

> Openstreetmap Schweiz/Suisse/Svizzera/Svizra

### What is it?
mailing list

### URL link to the resource
http://lists.openstreetmap.ch/mailman/listinfo/talk-ch

### Points of contact
?

### Bounding polygon

> You can reference the `id` of an existing polygon already added
to this project under the `features/` folder.

Switzerland is not existing for now

> If no polygon exists, you can use http://geojson.io to draw a polygon
around where this community is active.  Save it to a `.geojson` file
or a gist, and add a publicly shareable link here.

Why it would be preferable over exporting border from OSM data and reducing accuracy a bit?

### Languages spoken (optional)
?

### Country codes (optional)
ch

### Add an emoji flag (optional)
hopefully we can avoid emoji

**Comment by das-g** [comment]
> ### Add an emoji flag (optional)
> 
> hopefully we can avoid emoji

For what it's worth, the emoji for the Swiss flag would be ":switzerland:".

**Comment by bhousel** [comment]
done in #263 

BTW @joostschouppe - you can add some text like "closes #231" to the commit message, and it will close the issue automatically when the commit is merged.. [here's more details on what magic words do this](https://help.github.com/en/articles/closing-issues-using-keywords).

**Comment by joostschouppe** [comment]
Oh wow, that's handy! Thanks for the tip, @bhousel 
I guess I should also get a local client, so I can more easily make corrections on commits and edit several files in one commit.
