### ISSUE TITLE
Add upcoming events?

### ISSUE THREAD

**Issue by bhousel** [osmlab/osm-community-index#25]
Some groups will have events (like local State of the Map conference, meetups, etc).
Should we add an upcoming events data to this index so that tools like iD can show the user when the group's next event will be?

**Comment by mmd-osm** [comment]
There's already https://wiki.openstreetmap.org/wiki/Current_events out there, and WeeklyOSM team already parses this list automatically. Would be good to leverage this one.

Again, duplication of maintenance is only adding more fragmentation. If for whatever reason you don't find this list useable, could you please make a proposal on how to improve it?

**Comment by Nakaner** [comment]
@bhousel Are you planning to collect events in a Git repository at GithHub? If so, please keep in mind that the wiki is much easier to use for people who are not developers and don't know who to use Git. In addition, GitHub is not translated into any language which is a huge barrier for participation. Not to mention the privacy problems due to the [collection of personal information by GitHub](https://help.github.com/articles/github-privacy-statement/) which is not necessary from my point of view to provide such a service.

I don't want to say that we have to stay with the wiki (a very active wiki editor made me thinking about replacing the wiki by something different) but any service which replaces the wiki or parts of it has to be as accessible as the wiki.

**Comment by bhousel** [comment]
from @mmd-osm:

> However, we also have to keep in mind that the Wiki basically allows everyone to add events, no matter or large or small they are, and publishing is immediate without any Pull Request fiddling, etc.. I guess you don't want to grant everyone write & commit access to this repo, which essentially means that we'd be losing a fair amount of flexibility here.

Actually I probably would accept almost any PR to this repo without really looking at it.  If somebody asks "Add our state of the map conference to our group", I'd just do it.  I'd also happily grant write and commit access to this repo to anybody who cares to help maintain it.

The success of [editor-layer-index](https://github.com/osmlab/editor-layer-index) proves that this model of contribution works pretty well.

from @Nakaner: 
> Are you planning to collect events in a Git repository at GithHub?

I was just thinking something simple like this:

```js
{
  "id": "Mapping-DC-meetup",
  "featureId": "dc_metro",
  "type": "meetup",
  "name": "Mapping DC",
  "description": "Improve OpenStreetMap in the DC area",
  "url": "https://mappingdc.org/",
  "contacts": [
    {"name": "Brian DeRocher", "email": "brian@derocher.org"}
  ],
  "events": [
    {"name": "April Meetup", "when": "2018-04-10 18:00", "url": "..."},
    {"name": "June Meetup", "when": "2018-06-12 18:00", "url": "..."},
    {"name": "August Meetup", "when": "2018-08-14 18:00", "url": "..."},
    {"name": "October Meetup", "when": "2018-10-09 18:00", "url": "..."}
  ]
}
```

iD could add a line for the next event, or nothing if there are no next events.  It's also a nice signal that a group is actually active.

This question is more for people who run the community resources - do you want your event to appear alongside to your group in a listing like this?  For example, I'm more interested to know if @openbrian finds this useful.  I don't have a strong opinion.

**Comment by bhousel** [comment]
If somebody wants to write a thing to scrape the wiki page and move the events into a more structured format, that would be great, but it's not something I know how to do.

For now I'm just going to add a very simple event array to the resources schema like described above.. We might end up using it, or not.

**Comment by mmd-osm** [comment]
> If somebody wants to write a thing to scrape the wiki page and move the events into a more structured format, that would be great, but it's not something I know how to do.

Fortunately, WeeklyOSM already have a working solution for this issue:

Wiki page: https://wiki.openstreetmap.org/wiki/Template:Calendar
Parsed result: https://osmbc.openstreetmap.de/calendar/preview

@Nakaner should have a link to the current repo, I don't have it at hand atm.

**Comment by Nakaner** [comment]
@mmd-osm wrote:
> @Nakaner should have a link to the current repo, I don't have it at hand atm.

https://github.com/ThomasBarris/osmcalendar

**Comment by wambacher** [comment]
@bhousel trying to create a calender using GitHub is a nightmare - for all those user, which never ever used github and are not able to.

Editing a wiki page (osm wiki or wikepedia) is well known to many users - github is not.

GitHub is for software development, not for replacing an application.

**Comment by bhousel** [comment]
> trying to create a calender using GitHub is a nightmare - for all those user, which never ever used github and are not able to.

Agreed - we're not trying to create a calendar!

**Comment by wambacher** [comment]
> Agreed - we're not trying to create a calendar!

what else?

**Comment by mmd-osm** [comment]
@wambacher : I think "We might end up using it, or not." is pretty clear. Let's see what the future brings, if there's lots of momentum in this repo, some sort of import of the existing wiki calendar is likely to happen.  I'm still not sure on how to link geoJSON information in the json with what we have in the Wiki. But that's not a priority for today or tomorrow.
