### ISSUE TITLE
Non-profit and Second Hand Shop icons

### ISSUE THREAD

**Issue by joni909** [osmlab/osm-community-index#251]
I wondered I someone could make icons for non-profit and second hands,
because they don't really fit in with commercial nor with retail.

It's just a question and a suggestion.
cheers
 and 
keep up the good work, all of you involved

**Comment by quincylvania** [comment]
@joni909 Thanks for the suggestion. I assume you meant to post in the iD project (the community index doesn't deal with presets), so I transferred it there for you: https://github.com/openstreetmap/iD/issues/6813
