### ISSUE TITLE
OSM-NYC meetup doesn't exist

### ISSUE THREAD

**Issue by bdon** [osmlab/osm-community-index#252]
Hi, noticed after editing that there's a link to a Meetup.com group that doesn't exist anymore:  https://github.com/osmlab/osm-community-index/blob/master/resources/north-america/united_states/OSM-NYC.json 

Thanks!

**Comment by bhousel** [comment]
Aww too bad 😢  Thanks for reporting - I removed the entry..

**Comment by bdon** [comment]
@bhousel thanks for the quick fix!
