### ISSUE TITLE
Request to add Netherlands OpenStreetMap Forum

### ISSUE THREAD

**Issue by pelderson** [osmlab/osm-community-index#264]

**Comment by pelderson** [comment]
I don't know why my entries in the form are not visible. I see the when I'm editing the message, not when it's displayed.

**Comment by pelderson** [comment]
## Community Resource Name

"Netherlands OpenStreetMap forum"

### What is it?

"forum"

### URL link to the resource

"https://forum.openstreetmap.org/viewforum.php?id=12"

### Points of contact

"Peter Elderson, pelderson@gmail.com"

### Bounding polygon

"https://drive.google.com/file/d/1IYJTi3D-jRe9Y1m2VRwlGqZz4bljwWc9/view?usp=sharing"

### Description (optional)

### Languages spoken (optional)

### Country codes (optional)

"nl"

### Add an emoji flag (optional)

**Comment by joostschouppe** [comment]
I didn't add an "order" tag, since there is only one channel.
Discussed with the Dutch community at https://forum.openstreetmap.org/viewtopic.php?id=67457 . Some people would like to add the mailing list as well, but it has very low level of activity.

**Comment by bhousel** [comment]
Done in #274
