### ISSUE TITLE
Copy communities from local-wg, localgroups

### ISSUE THREAD

**Issue by bhousel** [osmlab/osm-community-index#27]
From https://github.com/osmlab/osm-community-index/issues/16#issuecomment-374110069
Several lists already exist, we just need to copy them over and add bounding polygons.

https://github.com/osmus/local-wg
https://github.com/osmlab/localgroups

**Comment by bhousel** [comment]
- [X] Bay Area OpenStreetMappers
- [X] Central Pennsylvania OSM
- [ ] Chattanooga OSM
- [ ] Dallas Fort Worth OSM
- [ ] GeoPhilly
- [ ] MapMinnesota
- [X] Mapping DC
- [ ] Maptime ME
- [ ] Open Cleveland
- [ ] OpenDataSTL
- [ ] OpenStreetMap Boston
- [ ] OpenStreetMap Georgia
- [ ] OpenStreetMap North Puget Sound
- [ ] OpenStreetMap NYC
- [ ] OpenStreetMap Portland
- [ ] OpenStreetMap Seattle
- [ ] OpenStreetMap St. Louis Mid America Mappers
- [ ] OpenStreetMap Utah
- [ ] OpenStreetMap Colorado
- [ ] OSM Southern California
- [ ] OSM Tampa Bay
- [ ] OSM Wyoming
- [ ] PHXGeo
- [ ] South Bay OSM
- [ ] Western Slope OpenStreetMap

I'm going to slowly work my way through this list.  
I'll add a contributors guide in the next day or so, but I'd love if people can help out!

**Comment by bhousel** [comment]
Update:  the [CONTRIBUTING.md](https://github.com/osmlab/osm-community-index/blob/master/CONTRIBUTING.md) guide is done and the doc schemas are stable now. 

Adding a new resource is very easy!

* Add a **feature** `.geojson` file under `features/` folder
  * This is a boundary around where the resource is active
  * You can use [geojson.io](http://geojson.io) to create these
* Add a **resource** `.json` file under `resources/` folder
  * This contains info about what the resource is (slack, forum, mailing list, facebook, etc)
  * You can just copy and change an existing one
  * Several resources can share the same `.geojson` feature
* `npm run test`
  * This will build and check for errors and make the files pretty

**Comment by russdeffner** [comment]
Hi @bhousel - wondering how you think Colorado should be handled? We have a state-wide meetup, a 'half-state' meetup and 2 or 3 city-wide meetups. I think I would prefer to have OSM-Colorado be an 'umbrella' so anyone looking at CO would always find it, but could also see benefit to having the regional ones displayed/discoverable at the appropriate scale.

**Comment by russdeffner** [comment]
Ah, ok - I'm waiting for a reply from the western slope folks (Nolan) on other stuff, so I'll see what they think.  For now, for sure OSM-CO operates across the state (lately more often outside of Denver than in) so I'll make those changes, should I change featureId to "Colorado"?

**Comment by zlavergne** [comment]
@russdeffner Nolan is no longer in charge of the western slope meetups. Send me any questions you have and I'll make sure to get it squared away

**Comment by russdeffner** [comment]
@zlavergne - Hey Zack, thanks - I'll send you an email.
