### ISSUE TITLE
What's the `type` for a regular meetup?

### ISSUE THREAD

**Issue by rory** [osmlab/osm-community-index#293]
[Resources have a `type`](https://github.com/osmlab/osm-community-index/blob/624bf883d13b6bd37478904cc7b943fbb6ce1dcc/CONTRIBUTING.md), and there are various options. What should the type of a regular meetup be? There's `type: "meetup"` but that's for meetup.com hosted events. Is there a good `type` for non-meetup.com events?

**Comment by bhousel** [comment]
I'd probably use `group` for a non-Meetup meetup.
