### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by bhousel** [osmlab/osm-community-index#3]
It's already set up to create a source strings a file for Transifex.  I just need to add a project for it and type up docs.

**Comment by manfredbrandl** [comment]
For most resources there is a priority language for translation (for some regions there may be two or more priority languages). It would help a lot if people can see translation requirements on transifex for each language for resources where the language is considered priority separated from other translation requirements.

**Comment by bhousel** [comment]
> For most resources there is a priority language for translation (for some regions there may be two or more priority languages). It would help a lot if people can see translation requirements on transifex for each language for resources where the language is considered priority separated from other translation requirements.

This is a good suggestion - I will see if I can push these priority languages in comments, similarly to how we push the preset terms in iD.

**Comment by bhousel** [comment]
I'll do this after we figure out #20  (what to put in the description field)

**Comment by manfredbrandl** [comment]
#20 was closed via https://github.com/osmlab/osm-community-index/commit/6ec3f2a443322c7c4ac1de7789174fb31884d8e5 already.

**Comment by bhousel** [comment]
Thanks for the reminder @manfredbrandl 

I put the new translation resource here:
https://www.transifex.com/openstreetmap/id-editor/community/
