### ISSUE TITLE
OSM World Matrix community

### ISSUE THREAD

**Issue by MegaArthur** [osmlab/osm-community-index#305]
## Community Resource Name

OpenStreetMap World Matrix Community

### What is it?

A community built on Matrix, a decentralised chat ecosystem. The rooms are also bridged with the OSM World Discord.

### URL link to the resource

Community link: https://matrix.to/#/+osmworld:privacytools.io

Main room link: https://matrix.to/#/!oDhjtNSpfTCAUmKBwW:privacytools.io?via=privacytools.io&via=t2bot.io&via=matrix.org

### Points of contact

Not sure if understood, but I guess it means the contact to the admin.

It's @megaarthur:privacytools.io on Matrix or
minecrartek [at] protonmail.com

### Bounding polygon

Worldwide

**Comment by bhousel** [comment]
see discussion on #316 
I'm closing here unless someone from OSMF or CWG says they are ok with it.
