### ISSUE TITLE
Add osm-de matrix room :de:

### ISSUE THREAD

**Issue by duncanturk** [osmlab/osm-community-index#307]
## Community Resource Name
OpenStreetMap DE Matrix

### What is it?
matrix

### URL link to the resource

https://riot.im/app/#/room/%23osm-de:matrix.org

### Points of contact
Christopher Rossbach, public.cr@protonmail.ch

### Bounding polygon
germany

### Description (optional)
German Matrix chat room #osm-de:matrix.org . Join at https://riot.im/app/#/room/%23osm-de:matrix.org

### Languages spoken (optional)
de

### Country codes (optional)
de

### Add an emoji flag (optional)
:de:

**Comment by bhousel** [comment]
done in #308
