### ISSUE TITLE
Telegram Ghana

### ISSUE THREAD

**Issue by mfbehrens99** [osmlab/osm-community-index#311]
## Community Resource Name
OpenStreetMap Ghana Telegram

### What is it?
telegram

### URL link to the resource
https://t.me/osmghana

### Bounding polygon
192781

### Description (optional)
Join the OpenStreetMap Telegram Ghana at: {url}

### Languages spoken (optional)
en

### Country codes (optional)
gh

### Add an emoji flag (optional)
:gh:

**Comment by bhousel** [comment]
done in #306
