### ISSUE TITLE
Allow 3-letter language codes

### ISSUE THREAD

**Issue by seav** [osmlab/osm-community-index#32]
Not all languages have 2-letter language codes. This is especially true for developing countries.

**Comment by bhousel** [comment]
Sure, this seems fine..

Would it be ok to allow either ISO-639-1 (2 letter) or ISO-639-3 (3 letter) code in this field?
Or should we enforce 3 letter code always?
(I don't have a preference)

ref: http://www-01.sil.org/iso639-3/codes.asp

**Comment by seav** [comment]
I think it is trivial to allow both in the regex, like so: `^[a-z]{2,3}$`. So for the more common languages or those that have 2-letter codes, we can have `en`, `fr`, and `de`, while also allowing `brx` and `doi` (both of which are official languages in India).

**Comment by bhousel** [comment]
> I think it is trivial to allow both in the regex, like so: ^[a-z]{2,3}$. So for the more common languages or those that have 2-letter codes, we can have en, fr, and de, while also allowing brx and doi (both of which are official languages in India).

Sounds good - just updated the schema docs to reflect this..
