### ISSUE TITLE
Diversity groups (in generall)

### ISSUE THREAD

**Issue by ferdinand0101** [osmlab/osm-community-index#338]
Should "special interest" groups be added ?

This is more of a generall question.

## Community Resource Name

Diversity-talk

### What is it?
A mailing list focused on discussing issues related to diversity in OSM

### URL link to the resource
https://lists.openstreetmap.org/listinfo/diversity-talk

### Points of contact

diversity-talk-owner@openstreetmap.org

### Bounding polygon

001

### Languages spoken (optional)

"en"

**Comment by bhousel** [comment]
> Should "special interest" groups be added ?
> This is more of a generall question.

I'm ok with it, maybe we should add something like a `specialInterest` property to say what the group like this is for.

Also, I worry that we have too many groups.  What I mean by this is:  on the post-save screen on iD, or on http://openstreetmap.community, we are showing people too many things.  I really think the various communities should pare down these lists - i.e. remove things that aren't really used, or aren't really relevant to newcomers.  

I just took a through the recent mailing list archives for the diversity-talk list, and it really reads more like a working group for OSM leadership, not something that casual mappers would be interested in.

**Comment by ferdinand0101** [comment]
That's quite a good argument so I'd say either "hiding" them away or just letting the people interested in that special interest seek them out themselves, would seem like the best options
