### ISSUE TITLE
Add Galician community resources

### ISSUE THREAD

**Issue by Ivans-Git** [osmlab/osm-community-index#344]
I expose the following that I wrote in the other post:

https://github.com/openstreetmap/iD/issues/7495

It is about the Galician community in Galicia: https://openstreetmap.community/

There have been changes in the telegram link for this: https://t.me/osmgalicia

It would be interesting to add this twitter: https://twitter.com/xeoinquedos

And finally add that these things are in the Galician language! It would not hurt to add the Portuguese community within Galicia too, since there are things that we share...

Thanks a lot!

**Comment by Ivans-Git** [comment]
To save you work, how could I edit it myself?

**Comment by quincylvania** [comment]
You can review our [contribution guide](https://github.com/osmlab/osm-community-index/blob/master/CONTRIBUTING.md) and open a PR!

**Comment by Ivans-Git** [comment]
> You can review our [contribution guide](https://github.com/osmlab/osm-community-index/blob/master/CONTRIBUTING.md) and open a PR!

good, what is a pr? if I click edit it creates a fork

**Comment by Ivans-Git** [comment]
> You can review our [contribution guide](https://github.com/osmlab/osm-community-index/blob/master/CONTRIBUTING.md) and open a PR!

Can i add more than one twitter account?

**Comment by Ivans-Git** [comment]
Another question that I have is how the information that Portugal has is expanded to the territory of Galicia, it seems quite complicated, can someone do it for me?

**Comment by Ivans-Git** [comment]
> ¡Puedes revisar nuestra [guía de contribuciones](https://github.com/osmlab/osm-community-index/blob/master/CONTRIBUTING.md) y abrir un PR!

If you can make the change for me it would be great, since I am a novice: https://github.com/osmlab/osm-community-index/pull/345#issuecomment-610560720

**Comment by bhousel** [comment]
I fixed the Galicia Telegram link and added xeoinquedos Twitter

**Comment by Ivans-Git** [comment]
> I fixed the Galicia Telegram link and added xeoinquedos Twitter

Thanks, but there is a typo in the name, it's Xeoinquedos, not xeoinquetos. Thanks again!

**Comment by bhousel** [comment]
sorry about that @Ivans-Git , I just fixed the misspelling in 5fb53a6
