### ISSUE TITLE
Add Resource Type XMPP/Jabber

### ISSUE THREAD

**Issue by britiger** [osmlab/osm-community-index#347]
There are no type of resource for XMPP/Jabber Channels in  the index. Is it possible to  add this type? In Germany there are a channel(MUC) for Germany and the  Berlin area. In the  wiki I've found  more XMPP-MUCs if they are still active I will contact them to add these to the index.
After implement the new type I will add the XMPPs using a PR.

**Comment by bhousel** [comment]
Sounds good, I've added `xmpp` as a supported type.  It will render with a keyboard icon like IRC.
