### ISSUE TITLE
Add osm-at matrix room :at:

### ISSUE THREAD

**Issue by natrius** [osmlab/osm-community-index#348]
## Community Resource Name

OpenStreetMap AT Matrix

### What is it?

matrix

### URL link to the resource

https://riot.im/app/#/room/%23osm-at:matrix.org

### Points of contact

Stefan Kies, negreheb+osmcommunityindex@mailbox.org

### Bounding polygon

Österreich 
https://www.openstreetmap.org/relation/16239

### Description (optional)

https://www.openstreetmap.de/ 
Unofficial german Matrix channel for Austria

Für kurze Fragen oder zum planen von Aktionen oder Treffen gedacht. Für ausgedehnte und komplexe Fragen bitte im Forum ( https://forum.openstreetmap.org/ ) einen Thread erstellen.

### Languages spoken (optional)

de

### Country codes (optional)

at

### Add an emoji flag (optional)

:at:

**Comment by natrius** [comment]
For some reason it links to `+osm-at:matrix.org` while it should be `#osm-at:matrix.org` and the `%23` should be a `#` as well. So there is something wrong i guess? @bhousel

**Comment by bhousel** [comment]
Thanks for reporting @natrius  - I just renamed it to `#osm-at` and will publish an update now..
