### ISSUE TITLE
https://openstreetmap.community/ lists everything twice in Czech Republic

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/osm-community-index#360]
![screen01](https://user-images.githubusercontent.com/899988/89730487-3f6b1a80-da3f-11ea-8ca5-bb838608dd84.png)

**Comment by matkoniecz** [comment]
weird, it happens only sometimes and more and more rarely 

close as irreproducible?

**Comment by bhousel** [comment]
Ah yeah, I've seen this before this is a bug in Mapbox GL `queryRenderedFeatures`.  I can make the query results unique.

**Comment by matkoniecz** [comment]
That would be great!
