### ISSUE TITLE
Use matrix link accross the board?

### ISSUE THREAD

**Issue by joostschouppe** [osmlab/osm-community-index#366]
Hi,
I'm willing to fix this myself, just collecting some opinions first.

* The Matrix network can be used with several apps.
* there's several links to Matrix via Riot. However, this is now "wrong" because [Riot was renamed to Element](https://element.io/blog/welcome-to-element/). The links still work though
* The Matrix-link to a room looks a little more scary https://matrix.to/#/#osmpe:matrix.org than an app-link like https://app.element.io/#/room/#osmpe:matrix.org
* Some groups link to a Riot/Element Community page, like this: https://app.element.io/#/group/+osmbe:matrix.org . I don't believe that exists on Matrix itself.
* All the relevant files seem to be of the same type, matrix.
* Recently, the German link https://github.com/osmlab/osm-community-index/pull/365 was changed from Riot to Matrix style. the link is "ugly" though, I would expect https://matrix.to/#/#osm-de:tchncs.de to do exactly the same (not sure though!)

I would suggest we do change all the links to Matrix-style, unless the Community system is used

**Comment by jbelien** [comment]
I definitely support this idea!

---

- 👍 Since there are several ways to "connect" to Matrix using something more generic in our Community Index sounds indeed better ;
- 👍 The https://matrix.to/ page allows the user to choose which client he/she will use to connect to the room ;
- 👍 We are not dependent anymore on decision made by the Matrix clients : if Riot is renamed to Element or if a client is dropped, we don't have to change anything ;
- 👍 The https://matrix.to/ "landing page" link is indeed way cleaner than the full link (`https://matrix.to/#/#osmbe:matrix.org` vs `https://matrix.to/#/!SqvNXrBsvdGHYRyota:matrix.org?via=matrix.org&via=atticstudios.be&via=gnome.org`)

---

- 👎 The user is not directly connected to the room but has to go through a "landing page" (that being said, I think https://matrix.to/ is clear enough so this is not really an issue) ;

**Comment by joostschouppe** [comment]
Thank you both!

**Comment by joostschouppe** [comment]
Beste,

Met het traffic sign project
<https://github.com/osmbe/traffic-sign-project>gebruiken
we bij OpenStreetMap Belgium <https://openstreetmap.be/nl/> de
verkeersborden die jullie digitaliseren in de Verkeersborden Vlaanderen
databank. Hartelijk dank dat uw gemeente deze databank bijwerkt, dit is
bijzonder nuttig voor ons (en ongetwijfeld ook voor andere GPS-data
producenten).

Bij het digitaliseren van deze data in OpenStreetMap merkte ik enkele
inconsistenties op.

De belangrijkste lijkt me dat er een bord begin zone 30 (voor verkeer
richting noord) staat getekend ter hoogte van Marktplein 27
<https://www.geopunt.be/kaart?viewer_url=https%3A%2F%2Fmaps.geopunt.be%2Fresources%2Fapps%2FGeopunt-kaart_app%2Findex.html%3Fid%3D8ab2fc277f0c02eb017f878b12ff0452>.
Dit lijkt in strijd met de nieuwsberichten; en er is ook geen bijhorende
einde zone 30 bord daar. Ik ga ervan uit dat dit een foutje is.

Kleinere opmerkingen:
- Het einde zone30 bord voor wie van de Hoogstraat komt
<https://www.geopunt.be/kaart?viewer_url=https%3A%2F%2Fmaps.geopunt.be%2Fresources%2Fapps%2FGeopunt-kaart_app%2Findex.html%3Fid%3D8ab21c587f806620017f87a479d90014>en
naar Kapellestraat / Marktplein gaat zou geliquideerd moeten worden. Wie
naar Kapellestraat gaa, krijgt immers geen begin zone 30 meer te zien. Wie
naar Marktplein gaat passeert sowieso nog een einde zone 30 bord.
- De zone30 borden van de Kleine Cité
<https://www.geopunt.be/kaart?viewer_url=https%3A%2F%2Fmaps.geopunt.be%2Fresources%2Fapps%2FGeopunt-kaart_app%2Findex.html%3Fid%3D8ab21c587f806620017f87a4f8150015>
zijn overbodig geworden. Een fout is wel dat dit eenrichtingsverkeer is,
maar dat verkeer in tegenrichting met een algemeen verbodsbord wordt
tegengehouden, niet met het correcte verbodsbord.
- De plaatsing van het einde zone 30 bord op de Bergstraat richting centrum
is ambigue; hierdoor zou iemand die de Bolwerkstraat inrijdt, kunnen denken
dat het nog zone 30 is. Het algoritme van de Snelheidskaart Vlaanderen
schijnt dit ook te denken.

Op basis van Google Streetview (dat helaas niet gebruikt mag worden omdat
het geen open data is) merk ik nog dat wat oudere aanpassingen in de
databank niet doorgevoerd zijn in de Verkeersborden databank. We kijken uit
naar verdere aanvullingen in de databank!

Met vriendelijke groet,
-- 
Joost Schouppe
vrijwillig mapper en bestuurslid bij OpenStreetMap Belgium
OpenStreetMap <http://www.openstreetmap.org/user/joost%20schouppe/> |
Twitter <https://twitter.com/joostjakob> | LinkedIn
<https://www.linkedin.com/pub/joost-schouppe/48/939/603> | Meetup
<http://www.meetup.com/OpenStreetMap-Belgium/members/97979802/>

**Comment by jbelien** [comment]
@joostschouppe I think something went wrong in your mailer 😄
