### ISSUE TITLE
Adjust ranking of Irish community resources

### ISSUE THREAD

**Issue by DaCor1** [osmlab/osm-community-index#368]
An example, OSM Ireland has the following listed in the index

- Website
- Mailing list
- Telegram
- Facebook group
- Twitter

These show up in ID in the following order

1. Twitter
2. Telegram
3. Facebook group
4. Mailing List
5. Website

Is there some way to allow a preferred ranking to be applied to the list so that it would show in whatever order the local community deems to be most effective e.g. for Ireland, in terms of most active to least active, the following order would apply

1. Telegram
2. Mailing List
3. Facebook group
4. Twitter
5. Website

**Comment by bhousel** [comment]
Yes, there is an `order` field that allows communities to control the sort order.

The current values for the Ireland communities are:

* Ireland Twitter - `5`
* Ireland Telegram - `4`
* Ireland Facebook - `3`
* Ireland Mailing List - `2`
* Ireland Local Chapter website - `1`
* Ireland IRC - `-1`

So we can just change the numbers and they will sort differently.  

Also feel free to remove whatever resources you're not using.  If nobody is actively using IRC, it's better to just delete it than show it to people.

**Comment by bhousel** [comment]
I ended up just changing them to match the requested order, since I still had the files open from before.
> Telegram
>Mailing List
>Facebook group
>Twitter
>Website
