### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by maro-21** [osmlab/osm-community-index#392]
I don't know if it's a bug with Transifex or something with the commits.
You've recently added or corrected some strings, e.g. https://github.com/osmlab/osm-community-index/commit/eb5e18012747d085a291e8b3cb29900c5cbfaabf
They popped up on Transifex as modified that need to be translated, but the strings are still the old version:
![Transifex](https://user-images.githubusercontent.com/57260466/102015948-b2263280-3d5e-11eb-927c-ac5589b54440.png)

**Comment by bhousel** [comment]
I think this should be fixed now - I just fixed things on the transifex side so it will pull from the `main` branch now.
