### ISSUE TITLE
Add way to link specific territory

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/osm-community-index#393]
For example, lets say that I welcomed a new user ( like at https://www.openstreetmap.org/changeset/95848279#map=19/50.01753/19.86268&layers=N )

I want to link him list of places where (s)he may ask for help. It would be nice to have way to link to place on map with side panel already opened - right now I would need to add extra instructions about clicking on map to see useful things.

Right now I see no way to do it with https://openstreetmap.community/

**Comment by kmpoppe** [comment]
Is that what you had in mind, @matkoniecz ?
https://kmpoppe.github.io/osm-community-index/?map=52.69636107827347,-7.470703125000256
Of course, @bhousel I'd like to know your opinion as well :-D

**Comment by matkoniecz** [comment]
Yes! Is there a way to generate such link or is it necessary to build it manually?

**Comment by kmpoppe** [comment]
I might have let out an important detail ;-) In the box on the right hand side, the lowest entry says "Permalink". Every time you click on a new sport on the map somewhere, that link gets rebuilt. So you can just go to any place, click on the map and the copy the Permalink to your clipboard.

**Comment by matkoniecz** [comment]
Oh I see it now! Maybe add some divider? To avoid listing it like a community what could be a bit confusing?

**Comment by kmpoppe** [comment]
Something like this (update page)?

**Comment by matkoniecz** [comment]
Exactly!

**Comment by kmpoppe** [comment]
Do you think we might need anything else in that regard? What just struck me was that I didn't put the zoom level in the link, will do that later (currently the zoom is fixed to 7).
^Kai

**Comment by matkoniecz** [comment]
For permalink it would be nice to include it.

**Comment by kmpoppe** [comment]
@matkoniecz Zoom level is in, you can take another look.

**Comment by matkoniecz** [comment]
Thanks! It got even better :)
