### ISSUE TITLE
Structure of completeFeatureCollection.json

### ISSUE THREAD

**Issue by jbelien** [osmlab/osm-community-index#398]
Hello @bhousel ,

I see that the structure of `completeFeatureCollection.json` (previously `combined.geojson`) has changed in version 3.0.
Properties  `iso1A2`, `iso1A3`, `iso1N3`, `wikidata`, `nameEn`, `aliases`, `groups`, `callingCodes`, `m49`, `isoStatus`, `level`, `emojiFlag`, `roadSpeedUnit`, `roadHeightUnit`, `driveSide` are now gone.

Would it be possible to put it back ?
I'm using `nameEn` and `level` to "structure" the display on https://community.osm.be/ (now all the resources are displayed as "local", since there is no `level` anymore).

Thanks :)

**Comment by bhousel** [comment]
Sorry about that @jbelien - I didn't realize anyone else was using that file, and I should have asked before removing.  I'll put the country-coder properties back and publish an update today.

**Comment by jbelien** [comment]
No worries ! Thanks for the quick fix @bhousel 😃 

Update is already made on https://community.osm.be/ 🎉
