### ISSUE TITLE
Add Alaska and Hawaii to United States GeoJSON

### ISSUE THREAD

**Issue by 1ec5** [osmlab/osm-community-index#4]
[https://github.com/osmlab/osm-community-index/blob/master/sources/north-america/us/OSM-US-Slack.geojson](OSM-US-Slack.geojson) covers the contiguous 48 states but not Alaska and Hawaii.

**Comment by bhousel** [comment]
They're there, just need to zoom out.  I should convert it to a proper MultiPolygon.

**Comment by bhousel** [comment]
see also https://github.com/osmlab/editor-layer-index/issues/424#issuecomment-370704314

**Comment by bhousel** [comment]
This was fixed - it's a MultiPolygon now 
https://github.com/osmlab/osm-community-index/blob/master/features/north-america/us/usa_full.geojson
