### ISSUE TITLE
OSM World Discord group languages update

### ISSUE THREAD

**Issue by PeterLeGras** [osmlab/osm-community-index#406]
Although the main channel is English, the OSM World discord server now supports conversation in the following languages in dedicated channels;

- German
- Spanish
- French
- Italian
- Brazilian Portuguese
- Romanian
- Turkish

**Comment by GoodClover** [comment]
I am going to make a pull request for this,
However Brazilian Portuguese doesn't have an ISO 639-1 or 639-3 language code, which is what is required for this.

Should I add it as just `pt` for Portuguese?

**Comment by bhousel** [comment]
I took care of it in 0d9f222 - I ended up putting `pt-BR` for Portuguese.  I think downstream projects just display it as text anyway.
