### ISSUE TITLE
Broken linking for German Matrix

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/osm-community-index#407]
```
Kanał OpenStreetMap Niemcy na Matriksie
Wejdź na kanał #osm-de:matrix.org na https://matrix.to/#/!JoceisEAQRNMtpWVGm:matrix.org?via=matrix.org&via=fairydust.space&via=tchncs.de
```
![screen04](https://user-images.githubusercontent.com/899988/105024093-fab2c900-5a4b-11eb-8ece-b3b52ef32e4d.png)

Not sure what went wrong. Matrix entry? PL translation? iD?

**Comment by bhousel** [comment]
I'm not sure either - It looks correct here and on Transifex.
https://www.transifex.com/openstreetmap/id-editor/translate/#pl/community/187180589?q=text%3Amatrix

I don't see anything obvious in iD either, but if it's still happening you should open an issue on the iD GitHub.  
(Either iD has old data or maybe a browser extension you have installed is rewriting matrix urls?)
