### ISSUE TITLE
Rank Github lower in Poland

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/osm-community-index#413]
Not sure what is causing this but on https://openstreetmap.community/ if you click Poland GitHub is ranked above Telegram, and should be lower as it is relevant only to small group of people (and I got sidetracked into discovering that Discord is not listed at all...)

**Comment by bhousel** [comment]
You can add an `order` property to control how the resources are sorted:

from [CONTRIBUTING.md](https://github.com/osmlab/osm-community-index/blob/main/CONTRIBUTING.md):
> order - (optional) When several resources with same geography are present, this adjusts the display order (default = 0, higher numbers display more prominently)

**Comment by matkoniecz** [comment]
https://github.com/osmlab/osm-community-index/blob/main/resources/europe/poland/OSM-PL-github.json - I am planning order 0 to put it below Facebook (it is supposed to be default, but apparently something overrides it)
