### ISSUE TITLE
Moving global Discord above global subreddit?

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/osm-community-index#418]
https://www.reddit.com/r/openstreetmap/ seems fairly inactive compared to https://discord.gg/4smYkq3gzp

In addition, Reddit is filled with ads, popups etc
![screen05](https://user-images.githubusercontent.com/899988/107189022-efb6dd00-69e8-11eb-8b02-d2e8c24f561d.png)

On the other hand, Reddit is publicly available - while you need to have Discord account to even view anything.

Opening an issue first as I may be biased - I am quite active on Discord and dislike Reddit due to general culture there, ads, prominent awards that you pay for etc.

**Comment by matkoniecz** [comment]
I would be happy to make PR if that would be considered as a good idea.

**Comment by bhousel** [comment]
Sure, I agree Reddit has really slipped in quality the past few years..

I adjusted some of the orders in e953dff, and now they are like this:

- OSMF website: `10`
- Discord: `6`
- Telegram: `5`
- Twitter: `4`
- Facebook: `3`
- /r/openstreetmap subreddit: `2`
- help.openstreetmap.org: `-2`
- irc: `-4`

The numbers should reflect which community resources are most helpful / friendly / welcoming to new users, and I think this does a pretty good job.
