### ISSUE TITLE
Mailinglists: Link to Archive or Listinfo?

### ISSUE THREAD

**Issue by kmpoppe** [osmlab/osm-community-index#445]
Some links to the osm.org-Mailinglists link to their Archive-Directory (/pipermail/), with the majority instead linking to the Listinfo (/listinfo/) - While I'm at it, I'd like to change all there to the Listinfo.

Any objections?

**Comment by bhousel** [comment]
I agree - they should all go to the listinfo page.

**Comment by kmpoppe** [comment]
Okay, will happen later today :)
