### ISSUE TITLE
Matrix room for OSM - Afghanistan :afghanistan: 

### ISSUE THREAD

**Issue by ahangarha** [osmlab/osm-community-index#454]
### What is it?
Due to the lack of any active communication platform for OSM in Afghanistan, I decided to make a room on Matrix which is FLOSS and distributed. I know there is already one Facebook group but it is not public (which means what ever is being generated there, it gets buried there). Also there is no indication of activity on that group. So despite I requested to join that group, I don't think it is a good place (at least as the only place) for communication.

So I made this Matrix room which is public and easy to join.

### URL link to the resource
The room ID is `#OSM-AF:matrix.org`.

https://matrix.to/#/#OSM-AF:matrix.org

### Points of contact
Mostafa Ahangarha
- I will be in charge. My account on Matrix: [@ahangarha:matrix.org](https://matrix.to/#/@ahangarha:matrix.org)
- My email address is also `ahangarha (a) riseup . net`

### Bounding polygon

https://gist.github.com/ahangarha/8ff5bf5b387d0fe3b93ed2fe68865b28

### Description (optional)
Join the discussion room here: https://matrix.to/#/#OSM-AF:matrix.org

‫به اتاق گفتگو در این نشانی بپیوندید: https://matrix.to/#/#OSM-AF:matrix.org

### Languages spoken (optional)
fa, ps, en

### Country codes (optional)
af

### Add an emoji flag (optional)
:afghanistan:

**Comment by ahangarha** [comment]
I made issue to see if it is Ok I do this.

It seems you have done it. Am I right?

**Comment by bhousel** [comment]
> I made issue to see if it is Ok I do this. 
> It seems you have done it. Am I right?

Yep, @kmpoppe took care of it already 👍 
It will show up on https://openstreetmap.community soon
The data is fetched from a CDN that refreshes after a few hours.

**Comment by ahangarha** [comment]
Thank you
