### ISSUE TITLE
can we influence the order in presenting Communities?

### ISSUE THREAD

**Issue by mfrasca** [osmlab/osm-community-index#456]
looking at Panamá, considering the top 4 "communities":
![image](https://user-images.githubusercontent.com/122869/116416573-11617c80-a800-11eb-9af0-14b36d65f283.png)

- ranking 2nd and 4th: two "Official" resources, running on OSM servers.
- ranking 3rd: the Telegram group I founded, and I'm happy it does appear even if the activity is very limited.
- top one is the email address of [a local organization](https://wiki.openstreetmap.org/wiki/Talk:J%C3%B3venes_Mapeadores_Panam%C3%A1), coming to life periodically in correspondence with ESRI's Gis Day.
- ranking 8th: the most appropriate official mailing list for the wider area.

would it be possible to push the official forum to first position?
why is [talk-latam](https://lists.openstreetmap.org/listinfo/talk-latam) only 8th?
or what statistics does this tool use for ranking communities in the list?

**Comment by bhousel** [comment]
Smaller (by area) communities are ranked before than larger communities.  
(This is why YouthMappers chapter appears before Panama, before the LatAm IRC Channel).

When comparing communities of the same area, resources support an `order` property to adjust the order that they are ranked.  
(So we could show the Forum above the Telegram, or Telegram above Forum, whichever you prefer).

https://github.com/osmlab/osm-community-index/wiki/Contributing#resource-files
> **order** - (optional) When several resources with same geography are present, this adjusts the display order (default = 0, higher numbers display more prominently)

**Comment by mfrasca** [comment]
so I might add an `order` value to the three local panamanian entries, and hope to see them better ranked? I'll open a pull request with my hopefully informed and acceptable interpretation.
I saw other regions, and again YouthMappers are more prominent than the national forum.  I don't know what's your experience with them, but in my opinion the official regional forum should be favoured.

**Comment by mfrasca** [comment]
see #457
