### ISSUE TITLE
OSM Canada slack

### ISSUE THREAD

**Issue by james2432** [osmlab/osm-community-index#46]
## Community Resource Name
OsmCanada

### What is it?
Slack,
Website,
Tasking Manager

### URL link to the resource
Slack url: osm-ca.slack.com
Self-invite: https://slackinviteosmcanada.herokuapp.com/
Website: https://www.osmcanada.ca/
Tasking Manager: http://tasks.osmcanada.ca/

### Points of contact
LogicalViolinist (osm)

### Bounding polygon
Canada

### Description (optional)
Slack channel

### Languages spoken (optional)

EN and FR

### Country codes (optional)

ca

### Add an emoji flag (optional)
:canada:

**Comment by Undearius** [comment]
#51 

I started a pull request that can be added on to.
