### ISSUE TITLE
Release 5.x : folders resources/features "missing"

### ISSUE THREAD

**Issue by jbelien** [osmlab/osm-community-index#471]
Hello,

I was upgrading my "OpenStreetMap Community Index viewer" (https://github.com/jbelien/oci-viewer) to version 5.x but I realized folders `features` and `resources` are now not included anymore.

That's unfortunate since I use those (sub-)folders to create the hierarchy regions/countries in my "viewer".

Would it be possible to add those folders back ?

Thanks :)

**Comment by bhousel** [comment]
I can put them back, sorry!

**Comment by jbelien** [comment]
Thanks @bhousel ! :)

**Comment by jbelien** [comment]
When is the next release planned ?
So I put it in my agenda to continue the work on upgrading to v5 😄

**Comment by bhousel** [comment]
I was going to do a minor release when #474 is done, but I can do it later today.
