### ISSUE TITLE
Feature request: Add support for LinkedIn

### ISSUE THREAD

**Issue by donalhunt** [osmlab/osm-community-index#474]
A growing number of communities have a presence on LinkedIn now. It would be good to enable communities to link to their page / group on LinkedIn.

Current "companies" on LinkedIn:
- Fundación OpenStreetMap Chile
- Iranian OpenStreetMap Association
- OpenStreetMap Africa
- OpenStreetMap Belgium
- OpenStreetMap Brazil
- OpenStreetMap Cote D'Ivoire ( OSMCI)
- OpenStreetMap CZ
- OpenStreetMap Foundation
- OpenStreetMap Foundation Japan
- OpenStreetMap España
- OpenStreetMap France
- OpenStreetMap Ghana
- OpenStreetMap Ireland
- OpenStreetMap Japan
- OpenStreetMap Mali
- OpenStreetMap Uganda
- OpenStreetMap US
- OpenStreetMap Taiwan
- OpenStreetMap Togo

There are also a handful of groups...

Happy to do the legwork if the maintainers can provide a small amount of guidance. :)

**Comment by kmpoppe** [comment]
Hi Donal,

and THANKS for your contribution! I will look into adding LinkedIn (Logo and programmatic stuff) after consulting @bhousel if he's against it.

It would be immensely helpful if you put a table in this issue listing the name, the URL and the geographical area, preferably in an ISO 639 format, which could be just a country. If it's a regional group, a county or city or something would help.

Greetings to lively Cork!

Kai

**Comment by kmpoppe** [comment]
#423 shows how said list could look (ordered by region which makes adding the information easier)

**Comment by bhousel** [comment]
> and THANKS for your contribution! I will look into adding LinkedIn (Logo and programmatic stuff) after consulting @bhousel

Sure, this is ok with me.. I just added the support for `linkedin` type and added a logo for it in 46fd10a0 👍 
I will update the [contributing guide](https://github.com/osmlab/osm-community-index/wiki/Contributing) too.

**Comment by matkoniecz** [comment]
Though I would limit linking to cases where some community activity happens there.

**Comment by bhousel** [comment]
> Though I would limit linking to cases where some community activity happens there.

I agree.. Anyway the support for LinkedIn resource type has been added about 6 months ago, so I'm going to close this.
