### ISSUE TITLE
Feature Req : Add Matrix.org room

### ISSUE THREAD

**Issue by Sabering1** [osmlab/osm-community-index#475]
Maybe add a Matrix room, and bridge it over to the other platforms (Discord,IRC, etc,etc)

**Comment by bhousel** [comment]
We already do support a `matrix` resource type for communities that want to chat that way.
(here are some previous issues where we have added these: https://github.com/osmlab/osm-community-index/issues?q=is%3Aissue+matrix+is%3Aclosed)
