### ISSUE TITLE
"Map Minnesota Meetup" community resource doesn't exist anymore

### ISSUE THREAD

**Issue by AxelBoldt** [osmlab/osm-community-index#477]
After editing in Minnesota, USA, the iD editor presents the link https://www.meetup.com/Map-Minnesota/ to "Map Minnesota Meetup". But the meetup.com site says "Sorry, the group you're looking for doesn't exist."  So it should be removed from the community resource list.

**Comment by iandees** [comment]
Hmm, I thought I had already removed it. I will submit a PR.

**Comment by iandees** [comment]
I did in https://github.com/osmlab/osm-community-index/pull/442. I don't think iD has been released with a new version of the community index for a while.

**Comment by bhousel** [comment]
Thanks for the update @iandees and @AxelBoldt - there is unfortunately not much we can do about this.

For what it's worth, I did test with RapiD and I don't see the Map Minnesota Meetup, so it will be correct whenever iD starts pulling the newer community-index data files.
