### ISSUE TITLE
Missing Local Chapters

### ISSUE THREAD

**Issue by atomoil** [osmlab/osm-community-index#482]
Hi,

The following are marked as `type=osm` but should be `type=osm-lc` to mark them as Local Chapters

* [x] Argentina
* [x] Czechia
* [x] Democratic Republic of Congo
* [x] Japan
* [x] Kosovo
* [x] Oceania
* [x] Poland
* [x] Slovakia

Complete list of Local Chapters is here: https://wiki.osmfoundation.org/wiki/Local_Chapters

**Comment by bhousel** [comment]
I had some time today, so I updated these and added the missing ones 👍

**Comment by atomoil** [comment]
Ah thanks! 💖💖
