### ISSUE TITLE
osgeo-oceania missing strings[].community

### ISSUE THREAD

**Issue by atomoil** [osmlab/osm-community-index#483]
Hey,

I noticed that `osgeo-oceania` in `resources.json` doesn't have a `strings[].community` key but all of the other `type=osm-lc` do. It does have a `strings[].name`. I am writing something that consumes `osm-community-index`, so should my code use community if it exists or name if not, or is this something that should be dealt with here?

**Comment by bhousel** [comment]
I think you should be using the `name` string for display.
I added `community` string so that translators would have less work in situations where a bunch of resources have slightly different names.

**Comment by bhousel** [comment]
> For me, I think using `strings[].name` and if it's missing then using `strings[].community` would work.

Sounds good - I agree this sounds like a good approach 👍 

> Thanks for your amazing work!

You're welcome! 😁
