### ISSUE TITLE
Feature request: Multiple types support

### ISSUE THREAD

**Issue by vranki** [osmlab/osm-community-index#488]
With Matrix it's easy to build chat channels that are bridged to multiple messenger. It would be useful to be able to define multiple types for same resource. For example type=["matrix", "irc", "telegram"]. 

Also it should be possible to define join links for each of the messengers for easy joining.

**Comment by bhousel** [comment]
We can't really support multiple types easily, but for now it's ok to just add multiple .json files (1 per resource).
