### ISSUE TITLE
YouthMappers at UAM and YouthMappers ITU

### ISSUE THREAD

**Issue by Mahabarata** [osmlab/osm-community-index#494]
Hi,

in transifex, we have to translate the text "YouthMappers at UAM" (string 4981).
There isn't another text contening UAM and in wikipedia I found 6 universities with these 3 letters [UAM](https://en.wikipedia.org/wiki/UAM).

It should be great to know which one it is.

edit : same question with "YouthMappers ITU" (string 4997) which could be 4 universities.

Best regards

**Comment by bhousel** [comment]
The source strings are in `i18n/en.yaml`:

YouthMappers at UAM:
https://github.com/osmlab/osm-community-index/blob/4db24896d04c7463f4d968c5780df5c4909abec8/i18n/en.yaml#L1082-L1084

YouthMappers ITU:
https://github.com/osmlab/osm-community-index/blob/4db24896d04c7463f4d968c5780df5c4909abec8/i18n/en.yaml#L904-L907

<br/>
<br/>

These strings do become part of the "key" used for translation:

<img width="1228" alt="Screen Shot 2021-11-29 at 12 18 40 PM" src="https://user-images.githubusercontent.com/38784/143913693-4060431e-47aa-4cc4-afbc-0e2c5710e65d.png">

**Comment by Mahabarata** [comment]
OK, thanks a lot.
