### ISSUE TITLE
add talk-pacific

### ISSUE THREAD

**Issue by andrewharvey** [osmlab/osm-community-index#498]
## Community Resource Name

[talk-pacific](https://lists.openstreetmap.org/listinfo/talk-pacific)

### What is it?

mailing list

### URL link to the resource

https://lists.openstreetmap.org/listinfo/talk-pacific

### Location

Peoples of the 
Moana/Oceania/Pacific.

### Description (optional)

_example:  "Join our group here: {url}"_

### Languages spoken (optional)

_example: "en"_

### Points of contact (optional)

_List of people who moderate or manage the community.
Each should include both a name and email:
example:  "Ian Dees, ian@openstreetmap.us"_

**Comment by andrewharvey** [comment]
@mapmakerdavid @ViolaineDo I think we should try to get talk-pacific included in the community index here, so it pops up for mappers making edits in the region, what do you think?. Any particular country codes and language codes to use?

**Comment by bhousel** [comment]
Thanks, I'd like to help get this resource added!

You can browse https://ideditor.codes/ to see what country and region codes we currently have "built-in" support for.
These include ISO 3166-1 2 or 3 letter country codes, UN M.49 numeric codes, and supported Wikidata QIDs.

For example, "Oceania", code `009` includes this:
https://ideditor.codes/?code=Q538 

BUT - please don't feel that you're limited to using country and region codes. 
The software can support any custom geojson area, so we could just draw a big polygon around everything you want included and use that as the "location" for talk-pacific.

**Comment by bhousel** [comment]
I added this resource today with a broad geojson that covers the Pacific and coastal areas, and the common indigenous languages too (see below).  It will start showing up soon for mappers editing in the Pacific.  I'm happy to revise it if you want..

Hoping everyone in the Pacific OSM community is safe and well following last week's eruption and tsunami near Tonga.
Let me know how and if we can support you!

```js
{
  "id": "talk-pacific",
  "type": "mailinglist",
  "account": "talk-pacific",
  "locationSet": {"include": ["pacific.geojson"]},
  "languageCodes": ["en", "fr", "haw", "mi", "sm", "to", "ty"],
  "strings": {
    "description": "The regional OSM mailing list for and by the peoples of the Moana/Oceania/Pacific",
    "extendedDescription": "We would like this mailing list to support all peoples of the Pacific, in all of our diversity and aspirations, to share thoughts, questions, projects, and everything related to OpenStreetMap in our sea of islands."
  }
}
```
<img width="519" alt="Screen Shot 2022-01-18 at 12 47 02 PM" src="https://user-images.githubusercontent.com/38784/149990989-e45b585b-13be-47a7-b795-197d7a552ac7.png">

**Comment by andrewharvey** [comment]
I'd rather leave it to @mapmakerdavid and @ViolaineDo to make a call on the area, but I would assume because we already have dedicated mailing lists for AU, NZ, JP that those are excluded. I'd also move the border in from the Americas so coastal regions of the Americas don't fall within the area.

**Comment by ViolaineDo** [comment]
Hi,
Sounds ok for the language part/description, and i would remove Australia and New zealand borders who have their own mailing lists. Thats list was made for Pacific islands, to have their own space. Which is the reason why we didn't name it oceania mailing list. Is thats enough informations ? 
Best regards


Le 18 janvier 2022 12:02:15 GMT-10:00, Andrew Harvey ***@***.***> a écrit :
