### ISSUE TITLE
Just make this Python already

### ISSUE THREAD

**Issue by grischard** [osmlab/osm-community-index#5]
Does anyone have any serious objections if I replace the (very few) Javascript scripts in this repository with Python? It would make things so much easier with testing, publishing, dependency management, etc?

Python ate the osm world already, lets just use it. This whole repo is JSON files anyway.

(See also: https://github.com/osmlab/editor-layer-index/issues/168) 😜

**Comment by bhousel** [comment]
> It would make things so much easier with testing, publishing, dependency management, etc?

Closing, as these are already solved problems here 😉
