### ISSUE TITLE
OSM Nigeria twitter link actually goes to OSM Niger twitter

### ISSUE THREAD

**Issue by pedrito1414** [osmlab/osm-community-index#504]
Just an error in the link - OSM Nigeria is at https://twitter.com/OSMNigeria, not https://twitter.com/OSMNiger

(the OSM Niger link is correct btw)

**Comment by 1ec5** [comment]
Fixed in 3f6f7da0ed3fc29bd646875844a5d31fac090b89 and 8ed0f8893f04e628908090fa2077e7da4764ac1e. Thanks for pointing out the error!
