### ISSUE TITLE
Add links to data sources for each country

### ISSUE THREAD

**Issue by aawiseman** [osmlab/osm-community-index#510]
The https://wiki.openstreetmap.org/wiki/Contributors page has sections for each country with data sets that are opened for use in OSM, might be good to include that in the Index, or maybe some other way to note that there is data. Mainly I think it would be good to have some way for people to find the open data easier, I don't think https://wiki.openstreetmap.org/wiki/Contributors is very well known.

**Comment by bhousel** [comment]
I'm also glad the contributors page exists, but I dont think it's an appropriate resource for this index.  The community index is more for tracking resources where people can meet others or talk to someone about OpenStreetMap.
