### ISSUE TITLE
Update YouthMappers

### ISSUE THREAD

**Issue by danieldegroot2** [osmlab/osm-community-index#531]
- [ ] Update listed resources
-- (Cleanup inactive resources)
- [ ] Check for unlisted resources
- Cleanup `"type": "youthmappers"` from non-websites if a website is added, to be in line with other resources.

#### Communidade YouthMappers Mozambique
- [Facebook](https://www.facebook.com/YouthMappers1/) **was changed**, but no posts since 2018.

#### SAB ITC UoTwente
Unsure if there's still a YouthMappers Comittee here, although their 2022 president is the ex-president of YM UoGhana.

**Comment by bhousel** [comment]
> * Cleanup `"type": "youthmappers"` from non-websites if a website is added, to be in line with other resources.

what does this mean?

**Comment by danieldegroot2** [comment]
Usually one resource for YouthMappers is set as `"type": "youthmappers"` (this can be ie. a Facebook page).
There may be websites which are not listed yet, which should get `"type": "youthmappers"`. In turn, the non-website resource should be changed to a different `type` (ie. `"type": "facebook"`).
It is a reminder, that's all.

Optionally, _all_ non-website resources for youthmappers could drop the `youthmappers` type, as is done with other types (osm, group). However, I understand it is not always clear something is a YouthMappers group, so I am ok to keep the YouthMappers type on those resources where a website is not present.

**Comment by bhousel** [comment]
Yeah the point of the `youthmappers` type is to show the YouthMappers icon, so those resources should continue to use that type (even if they are links to facebook or something else).

**Comment by bhousel** [comment]
closing as stale - either this stuff was done already or it isn't important
