### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by danieldegroot2** [osmlab/osm-community-index#532]
Pull request(s) are at [/pulls](https://github.com/osmlab/osm-community-index/pulls).

### Sources
- Contact channels themselves and private messages where needed.
- Wiki (excl. re-checking channel lists for now)
- [Community Discourse](https://community.openstreetmap.org/c/communities/9)
- OSMCal
- (TM4); a couple otherwise missed which may be considered.

### Notes
- Facebook Groups (not Communities, Hashtags etc.) are also a facebook resource and have been added in addition to the regular page of a community in the past. At least entries with a Facebook page, but without a Facebook group.
- Possible sources: loomio/agendadulibre/mobilizon/usergroups/teams
-- Mainly French(/Canadian) resources and German mailing lists.
- [/dist/resources.json](https://github.com/osmlab/osm-community-index/blob/e6365084463353a74fdf654c9c31964ba3a80fd2/dist/resources.json) lists resources alphabetically.
- [Country Coder](https://ideditor.codes/) quick link.

#### OpenStreetMap Paraguay
- [ ] [Facebook](https://www.facebook.com/osmparaguay)

#### OpenStreetMap Ethiopia
Emerging links; I was told there are plans to develop these resources further.
- [ ] [Twitter](https://twitter.com/osmethiopia) (a few posts)
- [ ] [Facebook](https://www.facebook.com/Openstreetmap-Ethiopia-103621602328277) (no posts, but has contact details)
-- Email: [osmethiopia@gmail.com](mailto:osmethiopia@gmail.com)
- [ ] [Website](https://osmethiopia.netlify.app/) (mostly 'blank' currently, but has contact details)
- [ ] [Telegram](https://t.me/osmethiopia) **was updated**

#### OpenStreetMap España
- [ ] [Matrix](https://matrix.to/#/#osm-es:matrix.org)

##### OpenStreetMap Burgos
`-3.69604, 42.34393`
- [ ] [Twitter](https://twitter.com/osmburgos)

#### OpenStreetMap Niger
- [ ] [Facebook](https://www.facebook.com/osmniger/) **was updated**

#### OpenStreetMap Namibia
- [ ] [Twitter](https://twitter.com/OSMNamibia)

#### OpenStreetMap Bosnia and Herzegovina
- [ ] [Signal](https://signal.group/#CjQKIIgworOPp4_d7f62Ur3egNnLXcOIZuyeakk7TCTq75YHEhBTa9eTkMLynI0MWnaQejgD) **added to wiki March 2021**

#### OpenStreetMap Slovakia
- [ ] [Matrix](https://matrix.to/#/#freemap.sk:matrix.org)
- [ ] [Slack](https://join.slack.com/t/freemap/shared_invite/zt-3i8lpwyd-8loYopjvxir_JZW~gtmPkg)

#### OpenStreetMap Serbia
- [ ] [Facebook Group](https://www.facebook.com/groups/OpenStreetMapSrbija)

#### OpenStreetMap Egypt
- [ ] [Facebook](https://www.facebook.com/OpenstreetmapEg/)

#### OpenStreetMap Papua New Guinea
- [ ] [Facebook Group](https://www.facebook.com/groups/osmppg/) (Last direct post April 15, 2022)

#### OpenStreetMap Malaysia
- [ ] [Facebook Group](https://www.facebook.com/groups/openstreetmapMY/) (Last direct post March 25, 2022)

#### OpenStreetMap Sri Lanka
- [ ] [Facebook Group](https://www.facebook.com/groups/142058222659672) (Last direct post November 7, 2021)

#### OpenStreetMap Timor-Leste
- [ ] [Facebook Group](https://www.facebook.com/groups/815552739879158) (Created August 15, 2022)

#### OpenStreetMap Austria
Approved as OSMF Local Chapter in
https://wiki.osmfoundation.org/wiki/Board/Minutes/2022-04#Vote

https://twitter.com/osm_at/status/1561667396032778241

- **Can await official signing if needed**
Update [resources/europe/austria/osm-at.json](https://github.com/osmlab/osm-community-index/blob/main/resources/europe/austria/osm-at.json) from `"type": "osm",` to `"type": "osm-lc",`

See also: [Twitter post](https://twitter.com/osm_at/status/1527642935742943233)
> Wir, [OpenStreetMap Austria], sind nun als offizielles Local Chapter der [OpenStreetMap] Foundation für Österreich angenommen! 😀  Auf der [SotM] 2022 in Florenz erfolgt dann die offizielle Unterzeichnung des Agreements.

#### Humanitarian Student Mapping Group - Trier University (HuMap Trier)
Student group, primarily humanitarian contributions.
- locationSet: `[[6.67506, 49.74804]]` ([entrance to F-Gebäude](https://www.openstreetmap.org/node/4711999059))
- [Website](https://humap-trier.github.io/)
-- Email: [humap-trier@posteo.de](mailto:humap-trier@posteo.de)

#### Mannheimer Mapathons (MAMAPA)
Eingetragener Verein (and CartONG initiative), organises primarily humanitarian mapathons.
- locationSet: `[[8.47949, 49.48150]]` ([their office](https://www.openstreetmap.org/node/5686089360))
- [Website](https://mamapa.org/)
-- Email: [info@mamapa.org](mailto:info@mamapa.org)
-- Project leader: Dr. Robert Danziger; Mannheim - [director@mamapa.org](mailto:director@mamapa.org)
- [Facebook](https://www.facebook.com/mannheimermapathons/)

#### #MapeandoMeuBairro (MapeandoMeuBairro)
**to be considered** Non-profit association / non-governmental organisation (NGO), social movement
- locationSet: `[[32.56651, -25.96621]]` ([Maputo](https://www.openstreetmap.org/node/27565081))
- [Website](https://mapeandomeubairro.org/)
-- Email: [mapeandomeubairro@gmail.com](mailto:mapeandomeubairro@gmail.com)
- [Facebook](https://www.facebook.com/MapeandoMeuBairro/)
- [Twitter](https://twitter.com/MapMeuBairro)

#### Other
Semi-active (needs to be contacted).
- (Comoros): [Facebook](https://www.facebook.com/openstreetmapcomoros) (Nov 2021)
-- (had a SotM 2021 on so far unsuccesful community building project.); alt. contact [Geoffrey](https://www.openstreetmap.org/user/Kateregga1) (OpenMappingGrants)

Possible other resources.
- (NEP): [Facebook](https://www.facebook.com/groups/osmnepal/) (mirror?)
- (US): [Facebook](https://www.facebook.com/groups/osm.us/)
- (XK): FLOSSK facebook, etc.

### Inactive
Will not be updated in the initial pull request. May be considered. May still be a valid way to contact the community.
- (Gabon): [Twitter](https://twitter.com/OsmGabon) (March 2020); compare to facebook: Sep 2021

### Not checked yet
Countries which still need checking for updates include
- Albania (Telegram was [updated](https://t.me/joinchat/C1Bx60HYZ4ByK-Kll0ww5g) - from: #546 )
- Belarus
- Bulgaria
- Greece
- Moldova
- Montenegro
- North Macedonia
- Romania
- Slovenia

**Comment by bhousel** [comment]
closing as stale - either this stuff was done already or it isn't important
