### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by danieldegroot2** [osmlab/osm-community-index#534]
Some things may be useful to document;
- Whether (some) edge cases are allowed (no offense to any of these; you can answer this as a regular question here.)
-- Resource: WhatsApp, can have a share link, but could be a private invite-only group.
-- Resource: Tasking manager (see Hungary).
-- Resource: Global resources not yet accepted by OSMF. (#305, #166, [OpenStreetMap Facebook group](https://www.facebook.com/groups/2233301645))
-- Community: (Global) (movement) groups (HOTOSM, UNMappers, Missing Maps, MapBeks); see also #338.
-- Community: Initiatives which may mostly post news or facts (MapAmore).
-- Specific (OSM) projects (which are not allowed afaik). An exception could be [Participatory mapping in Tajikistan](https://wiki.openstreetmap.org/wiki/Tajikistan/Participatory_mapping_in_Tajikistan) ([Facebook](https://web.facebook.com/participatory.mapping.tj/)); is to create an OSM community in Tajikistan.
- Whether some format of a property such as locationSet may be prefered to for example optimize performance.
- Whether it's prefered to link to a WikiProject's main page or it can and should link to eg. a /Meetings page where available. See also #293.
- Whether Events should be only some highlighted (usually larger) events, or can be any Events. The user should be told it may be a better idea to use the event types (Meetup, possibly others in the future), or other websites (OSMCal, possibly Microcosms in the future) - and vice versa it may also be useful to say that the Events feature exists besides the event types.
- What are acceptable overlaps etc. for polygons.
-- (Add a link to NSI for additional smaller area polygons.)

**Comment by matkoniecz** [comment]
> Resource: Global resources not yet accepted by OSMF. 

Many of communities indexed here are not run by OSMF. https://github.com/osmlab/osm-community-index#what-is-it does not or imply such limitation. 

I looked at https://github.com/osmlab/osm-community-index/issues/166#issuecomment-403346416 and it was NOT rejected for not being OSMF run. In fact rejection reason would apply also if this mirror would be OSMF run.

**Comment by danieldegroot2** [comment]
> [...] https://github.com/osmlab/osm-community-index#what-is-it does not or imply such limitation.

This issue is intended to clarify -and document where needed- whether such limitations exist.

> I looked at [#166 (comment)](https://github.com/osmlab/osm-community-index/issues/166#issuecomment-403346416) and it was NOT rejected for not being OSMF run. [...]

This refers to https://github.com/osmlab/osm-community-index/issues/305#issuecomment-570803895 . Any global resource may or may not need to be accepted -not "run"- by OSMF. See also https://github.com/osmlab/osm-community-index/issues/485#issuecomment-911759299 .
Mastodon, which you refer to, has since been added (last month). OSM World Discord was previously also added.

> [...] In fact rejection reason would apply also if this mirror would be OSMF run.

This issue tries to clarify whether a given limitation exists at all -and when it applies-, not whether a resource will be added to the index if it's passed one limitation or another.

It seems I haven't added mirrors to the list for clarification (after all, whether mirrors are allowed is also not stated in the documentation as far as I can see), perhaps since it's somewhat more common sense.
I hope this resolves your inquiry.

**Comment by bhousel** [comment]
Generally speaking:

I would prefer for the people who run the communities and participate in them and take ownership of them to add their stuff to this index themselves.  I would prefer not to have random people seeking out resources to add to this index.  This is unfortunately why we have a bunch of mailing lists and IRC channels here that nobody uses.  I think that's a mistake and it reflects poorly on OSM.

This is a very general statement, but I think it can be a guiding principle that answers most of the questions posed by this issue about what belongs and what doesn't belong.

I do not think we need to spell out specific rules about what belongs and doesn't belong.

Also, to be clear, this index has nothing to do with the OSMF.  We list the OSMF as a community resource, but they don't have to "accept" a resource to make it a thing.

**Comment by danieldegroot2** [comment]
I understand. I'll close this issue as resolved.
