### ISSUE TITLE
Schema: Add Eventbrite resource type

### ISSUE THREAD

**Issue by danieldegroot2** [osmlab/osm-community-index#535]
Eventbrite is an events website -just like Meetup- which is used by some groups (some may not be listed yet).

Type: `eventbrite`
Properties: Assume the same properties as `meetup`.
Example: https://www.eventbrite.nl/o/crowd2map-tanzania-14339957932 (Crowd2Map Tanzania)

(Icon does not seem to exist on Fontawesome.)

**Comment by bhousel** [comment]
The point of `type` is mostly just to pick which icon to show - so if there isn't a dedicated icon for eventbrite, I think it's fine to just use `group`.

List of types is here:  https://github.com/osmlab/osm-community-index/wiki/Contributing#type-required-account-optional

**Comment by danieldegroot2** [comment]
Thanks for the reply.

_Related issue on FontAwesome Github: https://github.com/FortAwesome/Font-Awesome/issues/428._
