### ISSUE TITLE
wiki.freemap.sk appears to be inactive  

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/osm-community-index#537]
http://wiki.freemap.sk/HomePage linked from https://openstreetmap.community/?map=48.85951,19.28713&zoom=9.52 has banner with

> Pozor! wiki.freemap.sk je archivovaná a už do nej nie je možné prispievať. Užitočné stránky budú premigrované na [oficiálne wiki stránky slovenskej OpenStreetMap komunity](https://wiki.openstreetmap.org/wiki/Sk:WikiProjekt_Slovensko).

autotranslated to

> WARNING! wiki.freemap.sk is archived and it is no longer possible to contribute to it. Useful pages will be migrated to the official wiki pages of the Slovak OpenStreetMap community.

**Comment by danieldegroot2** [comment]
Thanks. I've put it in the backlog for #532, as the contact channels are also mentioned there. Feel free to update it to the new link ahead of me. It is located in [this file](https://github.com/osmlab/osm-community-index/blob/main/resources/europe/slovakia/sk-freemap-wiki.json).

I've also noticed the Matrix and Slack channels. They're half a year and a year old, so I think adding them is fine without having to look if they're active first. It'd be nice to know of course.
