### ISSUE TITLE
Remove "Openstreetmap Côte d'Ivoire" Telegram chat - it is actually a dead announcement channel

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/osm-community-index#538]
It is mismatching other Telegram channels where you may chat, this one is broadcast only.

Maybe it would be better to describe it specially? Or maybe there is an actual chat channel?

**Comment by danieldegroot2** [comment]
You can add a [`description`](https://github.com/osmlab/osm-community-index/blob/e6365084463353a74fdf654c9c31964ba3a80fd2/schema/resource.json#L90) ([info](https://github.com/osmlab/osm-community-index/wiki/Contributing#strings-required)) to [this file](https://github.com/osmlab/osm-community-index/blob/main/resources/africa/cote_d'_ivoire/ci-telegram-osm.json). For example, `"description": "Announcements for activities of {community}. You can not send messages here.",` (people will see this description in iD when saving their edits.)

More importantly, has it had any messages recently? (in past two/three years)
If you can't see messages, try sending a message to `openstreetmapci@gmail.com` and/or [their Facebook page](https://www.facebook.com/openstreetmapci),

**Comment by matkoniecz** [comment]
Good point. Last activity was in 2019.

**Comment by danieldegroot2** [comment]
> I would propose to simply remove it as a dead project.

Ok. Feel free to submit a pull request.
