### ISSUE TITLE
List https://community.openstreetmap.org

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/osm-community-index#543]
## Community Resource Name

OpenStreetMap Community

(official OpenStreetMap forum?)

### What is it?

forum

### URL link to the resource

https://community.openstreetmap.org

### Location

world

### Description (optional)

?

### Languages spoken (optional)

?

### Points of contact (optional)

?

**Comment by matkoniecz** [comment]
See also https://community.openstreetmap.org/t/https-github-com-osmlab-osm-community-index-listing/1629

**Comment by bhousel** [comment]
Oh yeah this was already done in #530 a few weeks ago, I just haven't pushed a release yet.  (I wanted to give translators time to catch up to all the recent changes).
