### ISSUE TITLE
Alabania telegram channel is broken

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/osm-community-index#546]
it is a dead link

nothing is listed on https://wiki.openstreetmap.org/wiki/List_of_OSM_centric_Telegram_accounts

**Comment by danieldegroot2** [comment]
@bhousel [WikiProject](https://wiki.openstreetmap.org/wiki/WikiProject_Albania) lists https://t.me/joinchat/C1Bx60HYZ4ByK-Kll0ww5g though..

**Comment by matkoniecz** [comment]
@danieldegroot2 I guess that new issue for that would be a good idea if that channel is active

**Comment by danieldegroot2** [comment]
Index: Added 2018 [here](https://github.com/osmlab/osm-community-index/commit/7ce78173441e37f1be6393cf8a52abd84b35edbd)
Wiki: Added 2020 [here](https://wiki.openstreetmap.org/w/index.php?title=WikiProject_Albania&type=revision&diff=1982757&oldid=1982755) (working link with several online members already gives it away somewhat)

[old link](https://telegram.me/OpenStreetMapAL) looks like a valid account on first sight -it is not a group, true-, but may no longer be active.
![image](https://user-images.githubusercontent.com/67521919/174666629-e5a0b7a6-ad64-480d-b6f4-fe041261f353.png)
