### ISSUE TITLE
LF or CRLF or don't care?

### ISSUE THREAD

**Issue by kmpoppe** [osmlab/osm-community-index#548]
When running `npm run build` in Windows, the scripts convert all line breaks to `LF` where the bulk of files has the Linux style `CRLF`.

I'm severely lacking NPM skills to figure how to fix this, or if @bhousel you'd like this to be fixed anyway?

K

**Comment by bhousel** [comment]
Thanks for raising this  - I added a `.gitattributes` file that should set all the text files to `LF` when git touches them.
This answer contains some more info:  https://stackoverflow.com/a/42135910/7620

If your local copy of the repository has a mix of line endings, I think these steps should fix things to `LF` and it should stay that way going forward:
```bash
git pull origin       # Get the .gitattributes file
git rm --cached -r .  # Remove every file from git's index.
git reset --hard      # Rewrite git's index to pick up all the new line endings.
```

**Comment by kmpoppe** [comment]
Works like a charm, thanks :-)
