### ISSUE TITLE
Add mastodon account

### ISSUE THREAD

**Issue by sedrubal** [osmlab/osm-community-index#550]
## Community Resource Name

OpenStreetMap Account on en.osm.town

### What is it?

mastodon account

### URL link to the resource

https://en.osm.town/@openstreetmap

### Location

worldwide

### Description (optional)

Follow on Mastodon: {url}

### Languages spoken (optional)

en

### Points of contact (optional)

*I'm sorry, I don't know.*

**Comment by danieldegroot2** [comment]
Duplicate of https://github.com/osmlab/osm-community-index/issues/166#issuecomment-403346416.

**Comment by sedrubal** [comment]
I'm sorry...
