### ISSUE TITLE
Add link to North Korea Mapping Guide (OSM Wiki)

### ISSUE THREAD

**Issue by Koreller** [osmlab/osm-community-index#554]
## Community Resource Name

"OpenStreetMap North Korea Mapping Guide"

### What is it?

"mapping guide"

### URL link to the resource

https://wiki.openstreetmap.org/wiki/North_Korea_Mapping_Guide

### Location

"North Korea"

### Bounding polygon

relation: https://www.openstreetmap.org/relation/192734

### Description (optional)

(in english) "Mapping North Korea? Let's see what you can map with this extensive guide of the country."
(in french) "Envie de cartographier la Corée du Nord ? Voyez ce que vous pouvez faire avec ce guide complet du pays."

### Icon (optional)
Is there a wiki icon for this kind of case?

### Languages spoken (optional)

"en", "fr"

### Points of contact (optional)

https://wiki.openstreetmap.org/wiki/Korea OSM Wiki
"Koreller"

**Comment by danieldegroot2** [comment]
The Community Index is meant for resources focusing on the community itself and ways to contact it, not on mapping guides.

This documentation link is linked on the Korea Wiki page. If you would like to include the Korea Wiki page in the Community Index, you'll have to add the contact links to this wiki page too and/or post events there.

I would recommend using the [Welcome Tool](https://welcome.osm.be/) and the Telegram to send new users the mapping guide along with the Community Index and other useful links.
