### ISSUE TITLE
OpenStreetMap Deep South

### ISSUE THREAD

**Issue by SherbetS44105** [osmlab/osm-community-index#559]
Louisiana, Mississippi, Alabama, Georgia, South Carolina

info and communication at wiki page: https://wiki.openstreetmap.org/wiki/OpenStreetMap_Deep_South

thanks.

**Comment by kmpoppe** [comment]
I'm gonna do that later, good for getting into stuff again.

**Comment by kmpoppe** [comment]
@bhousel I was looking at the iD Editor codes, it seems that the single US-states aren't recognized (tried Alabama with US-AL, US-ALA and Q173). Are there any plans on adding them? I mean, I had geojson.io open and could draw a line around the 5 states, but it's wouldn't be as accurate...

**Comment by SherbetS44105** [comment]
I can generate an accurate Geojson file if needed

**Comment by kmpoppe** [comment]
That would be great, thank you @SherbetS44105

**Comment by SherbetS44105** [comment]
https://cloud.disroot.org/s/RSiZGsdMiwcHAHw

see if this works
