### ISSUE TITLE
Add Linkedin ITA FRA SRB + further work

### ISSUE THREAD

**Issue by Seandebasti** [osmlab/osm-community-index#563]
Hi, I identified three groups on Linkedin at least.
I would like to add them myself to find a start in contributing to this project on Github. I often find some objects, I like to add, but I never started. Now, I like to begin.
Could you show me the JSON file for the only listed Chile Linkedin group, that I understand the structure. Thanks
After I probably have to do a Pull request - on which branch do I do that?

## Community Resource Name

[OpenStreetMap France on LinkedIn](https://www.linkedin.com/groups/4143506/)

### What is it?

groups

### URL link to the resource

FRA https://www.linkedin.com/groups/4143506/
ITA https://www.linkedin.com/groups/8971366/
SRB https://www.linkedin.com/groups/13782056/

### Location

fr, it, Serbia

### Languages spoken (optional)

french, italian, serbian

**Comment by bhousel** [comment]
Welcome!  As a first step read through the documentation on the project wiki about contributing..
https://github.com/osmlab/osm-community-index/wiki
Hope that should get you started!
