### ISSUE TITLE
Track languages used on each resource?

### ISSUE THREAD

**Issue by maxerickson** [osmlab/osm-community-index#6]
An example motivation would be https://www.reddit.com/r/openstreetmap/ which is relatively global but overwhelmingly uses English.

**Comment by bhousel** [comment]
My initial thought is to just localize all the sources to all the languages.  

I don't know how important this is, but I'd imagine at least sometimes people will be armchair mapping in another country and want to contact someone local for whatever reason.

**Comment by bhousel** [comment]
Sorry @maxerickson I was thinking about localizing the display strings which is totally different.
You are right we should track the languages spoken by each resource.

**Comment by manfredbrandl** [comment]
I commented something similarly at #3 to allow translators to see (missing) translations for resources where their language is spoken.
