### ISSUE TITLE
Ireland telegram invite is dead

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/osm-community-index#609]

**Comment by danieldegroot2** [comment]
Try the one listed on the wiki instead (added Dec 2019, vs Oct 2019). Otherwise, feel free to contact them.
https://wiki.openstreetmap.org/wiki/Ireland#Contact

**Comment by matkoniecz** [comment]
> Try the one listed on the wiki instead (added Dec 2019, vs Oct 2019)

also dead
