### ISSUE TITLE
Missing link from resource to translated community name?

### ISSUE THREAD

**Issue by gravitystorm** [osmlab/osm-community-index#616]
I'm opening this here for additional visibility, and the original issue is open over on the openstreetmap-website repository at https://github.com/openstreetmap/openstreetmap-website/issues/3814

I'm unable to figure out how to get the translated name for a resource, when the translation uses fallbacks based on the resource type. 

For example, given the [fr-chapter](https://github.com/osmlab/osm-community-index/blob/d31da8c976ce589c79d01b1a7bd6ac924610a1df/resources/europe/france/fr-chapter.json) resource, I can look up the [`fr-chapter`](https://github.com/osmlab/osm-community-index/blob/d31da8c976ce589c79d01b1a7bd6ac924610a1df/i18n/pl.yaml#L353-L354) entry in `i18n/pl.yml`. 

```yaml
pl:
  fr-chapter:
    description: Pomagamy rozwijać i ulepszać OpenStreetMap we Francji.
```

There is no `name:` there, so I then look up the translation defaults for the resource type in order to determine the fallback string - i.e. [`pl._defaults.osm-lc`](https://github.com/osmlab/osm-community-index/blob/d31da8c976ce589c79d01b1a7bd6ac924610a1df/i18n/pl.yaml#L229-L230). This gives

```yaml
pl:
  _defaults:
    osm-lc:
      name: '{community}'
```

Finally, and this is where I get stuck, I need to know which community to put in there. I mean, I personally know that it's supposed to be `pl._communities.openstreetmapfrance: OpenStreetMap Francja`. However, I can't find any link - either in the translations file or in any resources file - that has the mapping from `fr-chapter` -> `openstreetmapfrance`.

Any guidance would be greatly appreciated!

**Comment by 1ec5** [comment]
If I’m not mistaken:

https://github.com/osmlab/osm-community-index/blob/d31da8c976ce589c79d01b1a7bd6ac924610a1df/lib/resolve_strings.js#L36-L39 https://github.com/osmlab/osm-community-index/blob/d31da8c976ce589c79d01b1a7bd6ac924610a1df/resources/europe/france/fr-chapter.json#L8 https://github.com/osmlab/osm-community-index/blob/d31da8c976ce589c79d01b1a7bd6ac924610a1df/lib/simplify.js#L3-L5

**Comment by gravitystorm** [comment]
Right, got you. I really didn't expect the translation key to be derived from a string value like that!

Thanks for the insight.

**Comment by bhousel** [comment]
I guess most of the context is on https://github.com/osmlab/osm-community-index/issues/30#issuecomment-818261808 and the comments after that one.  We had wanted for a while to use default strings and some method of putting strings together to make less work for our volunteer translators. 

So yeah, I'm ok with changing it so that we store the generated `communityID` with the resource, then consumers don't need to generate it at runtime.

**Comment by atomoil** [comment]
hey! I am up for picking this up, as I'd rather it was done in this project than re-implemented in the osm website's code. @bhousel can you give me any hints or tips on where in the code to add this, please?

**Comment by gravitystorm** [comment]
I think this will depend on how the maintainers want it to be implemented, and the main choice is whether the attribute should be generated in just the output files (i.e. `dist/resources.*`) or also included in the source files (under `resources/`). For our purposes, adding the attribute only in the `dist` files would be fine, and it's easier to implement that way too. 

I'd look at adding a `communityID` attribute to the code somewhere around: https://github.com/osmlab/osm-community-index/blob/8ffdb281d559e76c14244adfcc5bdcf6fcbde2ed/scripts/build_index.js#L241

Of course, the maintainers might have a better approach in mind!

**Comment by bhousel** [comment]
> I'd look at adding a `communityID` attribute to the code somewhere around:

☝️  I did this..
Now the build script saves the generated `communityID` alongside the `community` string.
This new attribute is persisted in all the `resources/*` files, and also in the `dist/resources.*` files too.

**Comment by atomoil** [comment]
Amazing, thank you @bhousel 🤩
