### ISSUE TITLE
Add Turkey Telegram Community

### ISSUE THREAD

**Issue by ahmetlii** [osmlab/osm-community-index#641]
## Community Resource Name

"OpenStreetMap Turkey Telegram"
### What is it?

"telegram"
### URL link to the resource

https://t.me/osm_tr
### Location

tr

**Comment by matkoniecz** [comment]
Is it a premium channel requiring payment to use?

**Comment by ahmetlii** [comment]
@matkoniecz no? as far as I am aware it doesn't, and there's that there aren't any channels on telegram that is exclusive for premium subscribers (similar to discord's nitro). The situation might arise only if the account has joined 500 groups/supergroups, and telegram doesn't allow more without its premium subscription. And this has nothing to do with the telegram channel.

**Comment by kmpoppe** [comment]
I was perfectly able to join the group and google-translate the group rules, I wonder what happened when #610 was behaving premium-ish 🤔

**Comment by 1ec5** [comment]
@matkoniecz, do you remember what you were seeing when you opened #610? I’ve joined several Telegram channels moderated by users who have premium subscriptions, but the only effect I’m aware of is that they’re able to post emoji that I can’t post myself.

**Comment by matkoniecz** [comment]
> do you remember what you were seeing when you opened https://github.com/osmlab/osm-community-index/issues/610

I was unable to join with regular Telegram software and was getting message that I need to have Telegram Premium (or I was able to join or was kicked immediately with such message, do not remember exact method).

I  never seen something like that before.

**Comment by kmpoppe** [comment]
The non-premium limit is 500 channels and large groups, after that you'd need Premium.

Are you joined to _that_ many groups?

**Comment by matkoniecz** [comment]
Definitely not.

Though maybe there is some limit on group member count and it was reached due to spambot wave? Or Telegram went silly?

I am unable to check again as Telegram made impossible to login without using their app, you cannot log in using password.

**Comment by matkoniecz** [comment]
I got PM from moderator of that telegram group and what is happening is that there is some bot/anti-spam measure that works in a following way:

- Telegram premium users are let in automatically, nonpaying ones may be kicked
- people not paying for Telegram premium are manually invited if they are not looking like spambots
