### ISSUE TITLE
Distinguish Official OSM forum and Discourse in general

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/osm-community-index#644]
for example https://github.com/matkoniecz/osm-community-index/blob/f45f979f26dbbe679b9094e2029d3e2a86b4cca9/resources/europe/poland/OSM-PL-discourse.json has `  "type": "discourse",`

maybe `  "type": "official_osm_forum",` would be better? The primary info is that it is OSMF run space, where you can log in with your OSM account and so on, right?

Not the implementation detail which software powers it.

And of community (for example in Iran, I think) is using Discourse forum setup somewhere separately then it should be shown differently...

**Comment by bhousel** [comment]
I really don't want to do any additional development to highlight the "official OSM forum run by the OSMF".  If this is information that is important to the OSMF, can you just update the description / extendedDescription properties to include this detail?
