### ISSUE TITLE
Use Travis + the Meetup API to populate upcomming events

### ISSUE THREAD

**Issue by nschonni** [osmlab/osm-community-index#65]
From the comment https://github.com/osmlab/osm-community-index/pull/63#issuecomment-379814213 it sounds like having the extra metadata will show the actual meetup events.

Looking at the Meetup API https://www.meetup.com/meetup_api/docs/find/upcoming_events/ it seems like that meeting info could be periodically scraped. EX: https://api.meetup.com/open-cleveland/events?&sign=true&photo-host=public&page=5&status=upcoming

You might be able to use the Travis CI cron jobs to do this periodically https://docs.travis-ci.com/user/cron-jobs/

**Comment by bhousel** [comment]
stale
