### ISSUE TITLE
kosovo-flossk.json incorrectly refers to freemap slovakia

### ISSUE THREAD

**Issue by tomhughes** [osmlab/osm-community-index#657]
The community name and ID in kosovo-flossk.json is wrong and refers to slovakia instead of kosovo.

**Comment by aceman444** [comment]
Thanks.
https://github.com/osmlab/osm-community-index/commit/f127317fc2c785f66a793fd3528e3f2caff5cc60
It seems only the "community" attribute is wrong, others seem OK.
