### ISSUE TITLE
Changelog entry dates are wrong for 2023 releases

### ISSUE THREAD

**Issue by vgeorge** [osmlab/osm-community-index#658]
These lines look wrong:

- https://github.com/osmlab/osm-community-index/blob/9c5e68f9bcef0e6486a4f04301e003c37e3c3588/CHANGELOG.md?plain=1#L23

- https://github.com/osmlab/osm-community-index/blob/9c5e68f9bcef0e6486a4f04301e003c37e3c3588/CHANGELOG.md?plain=1#L33

**Comment by bhousel** [comment]
oh whoops, thanks for noticing 🙈
