### ISSUE TITLE
Remove reddit?

### ISSUE THREAD

**Issue by bhousel** [osmlab/osm-community-index#662]
https://www.reddit.com/r/openstreetmap/ is unavailable because they are protesting something, so it seems silly to send people there.

**Comment by nielsswinkels** [comment]
Would it be an idea to add it back again? I was surprised to not see it in the list. I am no very active user, but I have seen posts of it come by my reddit feed. (Can't go look it up right now because reddit is down though.)

**Comment by bhousel** [comment]
> Would it be an idea to add it back again? I was surprised to not see it in the list. I am no very active user, but I have seen posts of it come by my reddit feed.

I'm ok with restoring it if if has some functional moderation back in place and someone from the OSM organization says it's ok.  (I'm also not a regular user there anymore, so I don't know).
