### ISSUE TITLE
OSM Gab 🐸 account is missing from "Like OpenStreetMap? Connect with others:" page

### ISSUE THREAD

**Issue by arbitrary-dev** [osmlab/osm-community-index#663]
Please create and add to the list.

**Comment by bhousel** [comment]
What is it?

**Comment by arbitrary-dev** [comment]
Like Twitter/Facebook but with freespeech and ban on various kinds of p*rnography.

**Comment by arbitrary-dev** [comment]
https://gab.com/

**Comment by bhousel** [comment]
Ok, but I don't think OSM has an account on there.  

We've also set the precedent with #316 that requests for "worldwide" resources should really loop in the OSMF or CWG (Communications Working Group) to make sure that our index isn't being misleading about which resources represent the OSM project in an official way.  So I'm going to have to close the request unless it comes from them - thanks for understanding!
