### ISSUE TITLE
Update Open Source San Jose Discord Link

### ISSUE THREAD

**Issue by ErikaVasNormandy** [osmlab/osm-community-index#667]
https://discord.gg/3bAd9DAWCp should be one of the permalinks as of 7/11/2023
![](https://files.slack.com/files-pri/T03EH1TH5-F05GGUCKCDB/image.png)

Michael also used https://discord.gg/rzFPZcE5vb

**Comment by 1ec5** [comment]
Thanks, this was fixed in #666.
