### ISSUE TITLE
Add Lemmy (or generic fediverse) category

### ISSUE THREAD

**Issue by pietervdvn** [osmlab/osm-community-index#670]
Hi,

As _another_ big social media platform is starting to fail due to enshittification, the [lemmy community for OpenStreetMap](https://lemmy.ml/c/openstreetmap) is gaining some traction. Lemmy is a Reddit-like social media network, based on ActivityPub.

With this issue, I would like to open the discussion to add a new category for this.

However, I'm not  sure which category would be best:

- We can create a generic `Fediverse`-category for any service supporting ActivityPub as protocol. As the fediverse space is quite young, I expect some more approaches to popup soon and a generic category could be a good catch-all. [Logo colours](https://joinfediverse.wiki/images/e/ec/Fediverse_logo.svg) [Logo B&W](https://joinfediverse.wiki/images/4/40/Fediverse.svg)
- We can create a Lemmy-category [Logo](https://joinfediverse.wiki/images/5/52/Lemmy_logo.svg)...
- ...but kbin exists as well, which is somewhat similar [Logo](https://joinfediverse.wiki/images/1/11/Kbin.svg)

If someone is really motivated, a category for _all_ Fediverse projects can be created. They are all listed on https://joinfediverse.wiki/What_are_Fediverse_projects%3F/Fancy

**Comment by bhousel** [comment]
Oh yeah I guess this is a followup from removing Reddit in #662 

My preference is to hold off for a few months and see what sticks around.
(Same as with Threads or Bluesky or any of they other new social platforms)

Also worth mentioning that we source the social logos from Font Awesome mostly, and they haven't made any logos yet for the new sites, so we may as well wait a few months for that to develop too.  
(The Lemmy logo you linked to is fine though - I could use it - I'd just rather wait and see if FontAwesome adds it to save me the work of doing it):
https://fontawesome.com/search?o=r&f=brands

The Fediverse stuff is pretty complicated and new - I don't know that normal users would understand it if we included a link to it on the Rapid post-save pane.

**Comment by pietervdvn** [comment]
> Oh yeah I guess this is a followup from removing Reddit in https://github.com/osmlab/osm-community-index/issues/662

Definitively related - even though the subreddit is 'public' again. I'm now a mod, but I'm actively promoting Lemmy. I don't expect the decline to go as fast as Twitter, but better safe then sorry

> My preference is to hold off for a few months and see what sticks around.

Definitively a valid strategy. In Dutch we have the saying "eerst de kat uit de boom kijken"

> The Fediverse stuff is pretty complicated and new - I don't know that normal users would understand it if we included a link to it on the Rapid post-save pane.

True, but all technology stuff was "pretty new" once upon a time. I suspect that people will sign up on the same instance that we link them too, as that is the easiest approach.

**Comment by 1ec5** [comment]
> I suspect that people will sign up on the same instance that we link them too, as that is the easiest approach.

That’s an interesting point. Along these lines, we currently link Discourse accounts to the original URL, but we could standardize on en.osm.town if we think that would make for a better OSM community experience.

**Comment by pietervdvn** [comment]
> That’s an interesting point. Along these lines, we currently link Mastodon accounts to the original URL, but we could standardize on en.osm.town if we think that would make for a better OSM community experience.

Yeah, that is something that could be done. If I understand you correctly, we can link to the Heigit-mastodon account by using either `https://mapstodon.space/@heigit` or as `https://en.osm.town/@heigit@mapstodon.space`.

This is something that has to be spoken through with Amanda (as she is the en.osm.town-admin).
Furthermore, this feels a bit unethical and some people will complain about this - so you will need to have good arguments to defend this.

**Comment by bhousel** [comment]
I cleaned up and added the "fediverse.svg" icon and added "fediverse" as a supported resource type.  
This will be pretty generic, same as "website" resources where people will just need to supply their own URL, but it will at least have that logo next to it.

I would also prefer for people who want to add resources like this, we can just use whatever link they want to use, not try to rewrite them to be `https://en.osm.town/` links.
