### ISSUE TITLE
Link of the organization "GeoMc" is not functional

### ISSUE THREAD

**Issue by Fchl3001** [osmlab/osm-community-index#674]
In "https://openstreetmap.community/" there is in DC this community called "GeoMc". When you click on its link, it sends you to an email called "stephanie.calderon@montgomerycollege.edu". I am part of Montgomery College, and this email does not seem to exist or is not accessible for some reason; for all the given reasons, it would probably be better to delete "GeoMc" from the osm-community-index database.

**Comment by bhousel** [comment]
Thanks @Fchl3001 , I removed it 👍
