### ISSUE TITLE
Remove OpenStreetMap World Discord?

### ISSUE THREAD

**Issue by bhousel** [osmlab/osm-community-index#688]
OSM World Discord has really dropped in quality lately.. Should we delist it from the community index?
I feel bad sending people to it.

![Screenshot 2023-10-27 at 3 34 02 PM](https://github.com/osmlab/osm-community-index/assets/38784/1c67c4dc-629b-446e-8c9d-ca85ac9fc70e)

**Comment by ZeLonewolf** [comment]
That seems like a rather extreme reaction to a disruptive incident that hasn't yet been adjudicated by the moderator team.

I've personally removed that particular block of offending content from the Discord server and the moderator team is discussing our next steps.  In the future, it would be helpful if disruptive content were flagged for moderator action as the first step.

**Comment by bhousel** [comment]
> That seems like a rather extreme reaction to a disruptive incident that hasn't yet been adjudicated by the moderator team.

Thanks, it's good to see that the Discord does have functioning moderation in place.  
I don't really see this as a one time incident - as I said it's a general slide in quality and I feel bad directing people towards it if it doesn't represent the OpenStreetMap project.  We hold the "worldwide" resources to a higher standard than local ones.

This project adds and remove resources from the index all the time, (we removed the Reddit in #662, and I imagine most of the mailing lists will be going away soon) so I don't see it as an extreme reaction.

**Comment by 501Ghost** [comment]
@bhousel You can contact the moderators directly on the server. IIRC it's as simple as typing `@modmail`.

**Comment by Atrate** [comment]
I'll add an update as part of the moderation team (speaking as part but not *for* everyone).

After a discussion among the mod team, the offending user (Sharko) has been banned from the OpenStreetMap World Discord server. Thanks for bringing such behavior to our attention, we strive to be a welcoming community and content seen on the provided screenshot should definitely not be something that a newcomer to the server or to OSM itself should see as the first thing to greet them.

> IIRC it's as simple as typing @modmail.

To be more specific: the go-to ways to contact staff on the OSMW Discord are to *send a direct message* to ModMail or mention @Moderator in any channel.

**Comment by 1ec5** [comment]
Speaking generally and not about this particular Discord server, there’s also an option to rank a resource lower in the list than other resources or rank regional/local resources higher, if the community that manages the resource feels that the extra prominent placement isn’t worth the extra pressure. The rankings are easy to tune based on feedback from the community.

**Comment by jxpsert** [comment]
Hi there! I'm the Jasper in this screenshot. The messages in this screenshot were a joke. The spoilered out message in the top said 'Holland' (which is not a correct name for the Netherlands). Sharko is from Wallonia - you can imagine the reasoning behind the messages that ensued.
