### ISSUE TITLE
Invalid "talk-al Mailing List" link

### ISSUE THREAD

**Issue by ivanbranco** [osmlab/osm-community-index#695]
Hi, after an edit in Albania the website suggest to join the talk-al Mailing List (https://lists.openstreetmap.org/listinfo/talk-al), but once clicked the website says "No such list talk-al". 

Maybe the link is wrong and should be fixed or the mailing list was deleted/never existed and should be deleted from the suggestions as well.

**Comment by bhousel** [comment]
Thanks for reporting, I'll remove it..
