### ISSUE TITLE
Split up data and polygons

### ISSUE THREAD

**Issue by bhousel** [osmlab/osm-community-index#7]
Before we go too wild adding all the things, we should separate the data from the polygons so that we don't run in to the kind of geojson duplication we see in editor-layer-index.

**Comment by bhousel** [comment]
This was done, now we have

`features/` - contains `.geojson` files, one for each feature.
`resources/` - contains `.json` files, one for each resource.

Each resource has a `featureId` to link it to a single feature.

**Comment by tyrasd** [comment]
Couldn't this been done also in a way that doesn't require at the separation into two files for each "region"? For example as an array property in the respective feature's `properties`, e.g. something like:

```
{
  "type": "Feature",
  "properties": {
    "id": "usa_full",
    "countryCode": "US",
    "resources": [
      {
          "type": "slack",
          "id": "OSM-US-Slack",
          "name": "OpenStreetMap US Slack",
          "description": "Sign up at {url}",
          "url": "https://osmus-slack.herokuapp.com/"
      },
      …
    ]
  },
  "geometry": {
    "type": "MultiPolygon",
    "coordinates": …
```

This would make maintenance and PRs easier, I believe.

A full separation between geometry and resource would only been needed if we would like to allow an n to m relationship between these (e.g. a joint inter-regional forum).

**Comment by bhousel** [comment]
> Couldn't this been done also in a way that doesn't require at the separation into two files for each "region"?

Yes, I considered that, but I think this way is:
- easier to explain to people
- reduces the need to edit the `.geojson`, which is more fragile
- better if community forums / meetups come and go but the features rarely change
- allows people to consume _just_ the resource list, if they don't care about the geometry

**Comment by tyrasd** [comment]
ok, I guess it comes down to a matter of taste ;), but:

* it can make it harder to create PRs (two files in separate directories vs. one single file which one can even do directly on github.com without even having to check out the repo locally)
* having hardcoded id strings as cross references is also a bit fragile. For example when removing a resource: do I have to check all other resources whether at least one still points to the respective geometry before deleting the geojson file as well? or do I just leave it in place in case something might re-use that geometry later on?
* consuming just the resource list would still be possible if you would provide it as a stripped down version of the "full" data in `/dist`
