### ISSUE TITLE
Instagram support

### ISSUE THREAD

**Issue by angoca** [osmlab/osm-community-index#710]
Are there any plans to add Instagram support?

Currently, there are a lot of accounts and users in this social network:

Global

* https://www.instagram.com/openstreetmap/

Europe

* https://www.instagram.com/openstreetmapuk/
* https://www.instagram.com/openstreetmap_italia/
* https://www.instagram.com/openstreetmap_albania/

Africa

* https://www.instagram.com/osmafrica/
* https://www.instagram.com/openstreetmap_uganda/
* https://www.instagram.com/openstreetmapethiopia/
* https://www.instagram.com/osmkenya/
* https://www.instagram.com/osmrwanda/
* https://www.instagram.com/openstreetmap_ng/
* https://www.instagram.com/openstreetmapmali/
* https://www.instagram.com/osmsouthsudan/
* https://www.instagram.com/osmbenin/

Asia

* https://www.instagram.com/openstreetmapjp/
* https://www.instagram.com/osmtunisia/

America

* https://www.instagram.com/openstreetmapus/
* https://www.instagram.com/osm_colombia/
* https://www.instagram.com/umbraosmbrasil/
* https://www.instagram.com/openstreetmapar/
* https://www.instagram.com/openstreetmappy/
* https://www.instagram.com/osm.peru/
* https://www.instagram.com/osm.vzla/
* https://www.instagram.com/osmpanama/
* https://www.instagram.com/openstreetmapsvg/

Local

* https://www.instagram.com/maptimebogota/
* https://www.instagram.com/polimappers/
* https://www.instagram.com/duitamamappingstars/
* https://www.instagram.com/osm_oeste_sc/

Is something similar for TikTok?

* https://www.tiktok.com/@openstreetmap_uganda
* https://www.tiktok.com/@openstreetmap.tg
* https://www.tiktok.com/@maptimebogota

**Comment by bhousel** [comment]
I hadn't really planned on it - some days I kinda feel like this index already has too much in it already.
