### ISSUE TITLE
OSM Cyprus Matrix Chat

### ISSUE THREAD

**Issue by Gafigglethorp** [osmlab/osm-community-index#718]
## Community Resource Name

OSM Cyprus Matrix Chat

### What is it?

Matrix room

### URL link to the resource

https://matrix.to/#/#osm-cyprus:matrix.org

### Location

Island of Cyprus

### Description (optional)

Although new and small, I hope that this will facilitate discussion across Cyprus for all contributors.

### Languages spoken (optional)

en

**Comment by bhousel** [comment]
done in #720
