### ISSUE TITLE
Deleted translations on transifex

### ISSUE THREAD

**Issue by kjonosm** [osmlab/osm-community-index#724]
Lots of translations have recently been deleted on transifex. What was the reason for that? Should these be retranslated?

**Comment by 1ec5** [comment]
Which language’s translations were deleted? The most recent change to the source strings was two months ago. Is it possible that the translations went away at that point, because they were outdated?

**Comment by bhousel** [comment]
I was running a script last week and it deleted the translations where the translated string exactly matches the English source string.

**Comment by kjonosm** [comment]
Hmm...Quite a few of the source strings don't need a translation because they match the original English version, especially when they refer to the name of a community, e.g. `OpenStreetMap DE` is the same in the English source string and the German translation.

For these cases, some translators (like me 😉) prefer to copy the English source string to mark a translation as complete and to be aware that whenever a new source string comes up it can quickly be picked up and translated.

So, if possible, please don't mass delete "untranslated" source strings.

**Comment by bhousel** [comment]
Yes I realized later that some people like to see those numbers say 100% , so I won’t delete the identical translations strings any more.

**Comment by matheusgomesms** [comment]
Sorry, I didn't quite understand. Redundancy in this case is that there is a lot of "OpenStreetMap USA" strings (for example), so just one translation is enough?

I'm not an expert on localization, but perhaps isn't better to fix the source strings, to not have duplicates there?

Also, regarding 100%, we translators use "Not translated" function to translate what is missing. If translations are deleted, it is:
1 - impossible what is duplicated or not
2 - harder to translate what is missing (indeed) or what is duplicate
