### ISSUE TITLE
Add a resource type for Signal messenger

### ISSUE THREAD

**Issue by bhousel** [osmlab/osm-community-index#737]
> Oh cool, this is the first `signal` group we've seen.  
> I should probably add it as a resource type.

_Originally posted by @bhousel in https://github.com/osmlab/osm-community-index/issues/735#issuecomment-2338901573_

**Comment by bhousel** [comment]
Oh wait I was wrong - we do support signal already, but we didn't use the FontAwesome icon.

**Comment by partytax** [comment]
Hah I was about to comment on original PR saying I found `signal` value in docs
