### ISSUE TITLE
Issue with 5.8.1 - unknown key {communauté} 

### ISSUE THREAD

**Issue by mmd-osm** [osmlab/osm-community-index#739]
In https://github.com/openstreetmap/openstreetmap-website/pull/5210 we're seeing build failures for this new release:

<img width="429" alt="{FF39377A-5975-40B3-9CC1-4C386A12062D}" src="https://github.com/user-attachments/assets/5f8b9e71-5cdd-422e-bdc2-fb4e3b4e8fa9">

It seems some translator changed the community key to the French translation `{communauté}`, which isn't known by our parser. I suppose anything in curly braces should not be touched by translators.

https://github.com/osmlab/osm-community-index/blob/bb49bd67e37777a366874530269e888d76511746/i18n/fr.yaml#L213

(and several others in the same file)

What would be the best way forward to fix this issue?  I cannot change the French translation on my own, since Transifex wants me to join the French translator group first. I haven't found a way to comment on French translations either, or find out who has worked on these changes.

By the way, maybe this could be somehow automated in unit tests, to make sure translations are using valid replacement tokens only.

**Comment by mmd-osm** [comment]
I've posted this one on the French community forum: https://forum.openstreetmap.fr/t/corriger-la-traduction-francaise-de-osm-community-index/27184

**Comment by etiennejourdier** [comment]
It's done, I corrected in transifex the {communauté} occurences back to {community} and much more {compte} to {account}:
https://app.transifex.com/openstreetmap/id-editor/translate/#fr/community/321118186?q=translator%3APlayGuide+translation_text%3A{
idea: write a generic script that checks that the words in curly braces have not been changed in the translations?

**Comment by bhousel** [comment]
> idea: write a generic script that checks that the words in curly braces have not been changed in the translations?

I actually think Transifex might have a built in checker for this - we might have to enable it.

**Comment by bhousel** [comment]
> I actually think Transifex might have a built in checker for this - we might have to enable it.

I updated the Translation Checks settings for all the OpenStreetMap and Rapid projects on Transifex so that it should now consider anything like `{...}` as a placeholder, and enforce stricter checks on those - i.e. not allow the user to translate them, and make sure the number of placeholders is the same in both the source and translation strings.  If there are mistakes, they will show up as errors on Transifex.
