### ISSUE TITLE
OpenStreetMap Chile

### ISSUE THREAD

**Issue by osmCL** [osmlab/osm-community-index#77]
OpenStreetMap Chile

Description in spanish for the current four channels (Facebook, Mailing List, Telegram and Twitter in that order) 

"description": "Únete a la comunidad de OpenStreetMap Chile en Facebook",
"extendedDescription": "Únete a la comunidad para aprender más sobre OpenStreetMap, realizar preguntas o participar en nuestras reuniones ¡Todos son bienvenidos!",

"description": "Una lista de correos para discutir sobre OpenStreetMap en Chile"

"description": "Únete a la comunidad de OpenStreetMap Chile en Telegram",
  "extendedDescription": "Únete a la comunidad para aprender más sobre OpenStreetMap, hacer preguntas o participar en nuestras reuniones ¡Todos son bienvenidos!"

"description": "Síguenos en Twitter en {url}"

cl

**Comment by osmCL** [comment]
Since the description areas in the issue template said "optional" I originally leaved them empty. But now if I go to the chilean JSON files I see that the descriptions and extendedDescriptions are in english. Is this always in English and supposed to be translated to any other language via Transifex?

**Comment by bhousel** [comment]
> Is this always in English and supposed to be translated to any other language via Transifex?

Yes - that's right!

**Comment by osmCL** [comment]
The transifex link gives me a 404 error. 

And if I go directly to https://www.transifex.com/openstreetmap/id-editor/ it says that there is 0 strings to translate in Spanish.

**Comment by bhousel** [comment]
> And if I go directly to https://www.transifex.com/openstreetmap/id-editor/ it says that there is 0 strings to translate in Spanish.

It looks like the strings are now translated.  The next version of iD should show them 👍
