### ISSUE TITLE
Chilean community data no showing when you edit in the middle of Chile

### ISSUE THREAD

**Issue by osmCL** [osmlab/osm-community-index#78]
I just saved a changeset in the middle of Chile (well inside Chiles geojson polygon) and iD only shows me the international Reddit 
![community-index-reddit](https://user-images.githubusercontent.com/28224747/38879816-9e0ad0e8-423a-11e8-8471-ccf0a260d45d.png)

**Comment by bhousel** [comment]
Thanks @osmCL - I will investigate, this seems wrong 🕵️

**Comment by bhousel** [comment]
> Reporting from Dubai, just show the internation Reddit as well

The index doesn't have any local communities for around Dubai.. If you know of any, please open an issue and we will add them..  😄

**Comment by bhousel** [comment]
> Thanks @osmCL - I will investigate, this seems wrong 🕵️

I checked this - the issue is on the iD side, so I'm going to close here..  I believe iD 2.8.0 shipped with a slightly older version of this index.  I have a bunch more resources to add, and I'll push an update this week..
