### ISSUE TITLE
Show this index on a map

### ISSUE THREAD

**Issue by bhousel** [osmlab/osm-community-index#79]
Kind of similar to how [editor-layer-index](https://github.com/osmlab/editor-layer-index) has a basic [live preview](https://osmlab.github.io/editor-layer-index/) - this index should have a map too.

**Comment by joostschouppe** [comment]
@jbelien suggested also turning this into a website. Basically, if you go to https://NICE-WEBSITE/north-america/us you get a pretty webpage that shows you the resources for the US resources.
Extras:
- add /language-code to get the page in different languages
- show the national resources first (e.g. by making sure files with national resources start with the country code, or adding it as a property to the JSON)
This would also make it a little easier for local organisers to add a page to their website where they show their media.

**Comment by jbelien** [comment]
Here are some screenshots !
I'll publish it on my GitHub account in the next few days ! 🎉 

Feel free to already made some comments about it !

---

http://localhost:8080/resources/europe/be :

![capture d ecran - 2018-05-06 a 11 30 17](https://user-images.githubusercontent.com/1150563/39671890-25db8e64-5121-11e8-8510-979edb306d52.png)

---

http://localhost:8080/resources/europe/be/fr (translation enabled) :

![capture d ecran - 2018-05-06 a 11 33 43](https://user-images.githubusercontent.com/1150563/39671902-5a11c25c-5121-11e8-85fb-bfbaf79f3b0a.png)

---

http://localhost:8080/features/europe/be :

![capture d ecran - 2018-05-06 a 11 34 52](https://user-images.githubusercontent.com/1150563/39671919-85be5474-5121-11e8-9b3d-97f7fcf8858c.png)

Translation is of course available for `/features` too.

--- 

I also added an `iframe` mode which removes the country title to embed the result in an iframe.

http://localhost:8080/resources/europe/be?iframe :

![capture d ecran - 2018-05-06 a 11 36 39](https://user-images.githubusercontent.com/1150563/39671941-c1f1cc46-5121-11e8-838f-4e709c38ae20.png)

**Comment by bhousel** [comment]
That's great @jbelien !   We can merge this and serve it on the github page for this project  👍

**Comment by jbelien** [comment]
Thanks for the good words ! 😄 

You can play with it here : https://community.osmbe.akoo.ovh/
Code will be published soon.

Unfortunately, it won't be possible to host it on GitHub Pages because it's developed using PHP.

**Comment by jbelien** [comment]
Code is (finally) released : https://github.com/jbelien/oci-viewer
And it is now run using Heroku : https://oci-viewer.herokuapp.com/ (http://community.osm.be/ will soon be redirected to the new Heroku app.)

**Comment by bhousel** [comment]
Hey @osmtools ! 
The release branch of this repo contains the generated files:
https://github.com/osmlab/osm-community-index/tree/release/dist

On iD side, we bundle the index directly into iD.  
But a site that just wants to import the index could load it in a `<script>` tag from https://unpkg.com/#/
(for example:  https://unpkg.com/osm-community-index )

I think we should add some better "how to use this index" info to the README with examples.






> Have a look at http://usergroups.openstreetmap.de/community.html
> 
> Because there isn't any hierarchy in the features some inner outlines are overlapped by the country outline and so the click event for the popup shows the _wrong_ information. But for Leaflet.geojson the sorting (hierarchy) is important, first the country outlines (admin=2), then regions (admin=4), then administrations (admin=6) on top and so on.

Oh yeah I see what you mean - you definitely want to sort the smallest areas on top of the larger areas.  In iD I use [d3.polygonArea](https://github.com/d3/d3-polygon#polygonArea) but something like [turf/area](https://www.npmjs.com/package/@turf/area) would work too.  Maybe we should just calculate the areas in this project and include them with each entry?  It would help out downstream projects..

**Comment by matkoniecz** [comment]
Would it be OK to start linking https://community.osm.be/ from the readme?

**Comment by bhousel** [comment]
> Would it be OK to start linking https://community.osm.be/ from the readme?

Sure 👍

**Comment by bhousel** [comment]
Quick update on this - as of [v0.11.0](https://github.com/osmlab/osm-community-index/blob/master/CHANGELOG.md#0110) we're now publishing a `combined.geojson` file which makes it a little easier for consumers to just get all the data and show it on a map.

If you want to use this file, you can get it from the `release` branch:
https://github.com/osmlab/osm-community-index/blob/release/dist/combined.geojson
https://github.com/osmlab/osm-community-index/blob/release/dist/combined.min.geojson

Or even better - use something like the [unpkg CDN](https://unpkg.com/) to fetch the latest published version of the file:
https://unpkg.com/osm-community-index/dist/combined.geojson
https://unpkg.com/osm-community-index/dist/combined.min.geojson

**Comment by jbelien** [comment]
Interesting! 🎉 

I'll try to add that to https://community.osm.be/ to display a global map ! 👍

**Comment by joostschouppe** [comment]
Mikel made a quick map: https://mikelmaron.github.io/map-demos/osm-community-index/

**Comment by bhousel** [comment]
> Mikel made a quick map: https://mikelmaron.github.io/map-demos/osm-community-index/

This is great!  Thanks @mikelmaron for putting this together.
I've added the link to the README file..

**Comment by jbelien** [comment]
Map deployed on https://community.osm.be/ 🎉

**Comment by jbelien** [comment]
I've built a new version of my OSM Community Index viewer : https://oci-viewer.netlify.app/ (temporary URL ; it will still use https://community.osm.be/ when released).

Interface has been improved and the website is now static (using [Sapper](https://sapper.svelte.dev/)) and could be hosted using GitHub Pages (see https://github.com/osmlab/osm-community-index/issues/79#issuecomment-387129284) !

Feedback is welcome :)
