### ISSUE TITLE
Add guide for adding resources

### ISSUE THREAD

**Issue by manfredbrandl** [osmlab/osm-community-index#8]
I would like to add two resources for Styria which is a part of Austria which is in Europe. It would help much if I can see in Readme.md how to do that. Do I have to create a folder styria inside the folder at inside Europe? Where do I put the geojson-files etc.

**Comment by manfredbrandl** [comment]
Maybe add a FAQ.md including the (somewhat modified) section "How can I draw a bounding polygon?" from ../editor-layer-index .

**Comment by bhousel** [comment]
Yes, I will add some documentation 👍 

The code is still in flux and changing a lot, but I think we can settle on something more stable in a few days.
