### ISSUE TITLE
linkify reddit

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/osm-community-index#82]
After my change I got

>  /r/openstreetmap/ is a great place to learn more about OpenStreetMap.  Ask us anything!

message. I think that "/r/openstreetmap/" should be a link leading to this community

**Comment by bhousel** [comment]
Good suggestion - this is really an issue for the iD repo.

**Comment by bhousel** [comment]
This issue was moved to openstreetmap/iD#4997

**Comment by matkoniecz** [comment]
Ops, link leading to this project suggested that it was provided by this data repository. Sorry for misfiling,
