### ISSUE TITLE
Add PH 🇵🇭 community

### ISSUE THREAD

**Issue by maning** [osmlab/osm-community-index#9]
Reference contacts: http://telegra.ph/OpenStreetMap-LoCo-channels-in-the-Philippines-02-15

cc @seav @gowin

**Comment by bhousel** [comment]
Update:  the [CONTRIBUTING.md](https://github.com/osmlab/osm-community-index/blob/master/CONTRIBUTING.md) guide is done and the doc schemas are stable now. 

See https://github.com/osmlab/osm-community-index/issues/27#issuecomment-377539650 for how to add the resources to the index.
