### ISSUE TITLE
osm-bolivia

### ISSUE THREAD

**Issue by 51114u9** [osmlab/osm-community-index#98]
## Community Resource Name

"OpenStreetMap Bolivia"

### What is it?

"mailing list"

### URL link to the resource

Mailing list: https://lists.openstreetmap.org/pipermail/talk-bo

### Points of contact

name: "Marco Antonio", email: "marcoantoniofrias@gmail.com"

### Bounding polygon

relation: https://www.openstreetmap.org/relation/252645

### Description (optional)

description: "Talk-bo is the official mailing list for the Bolivian OpenStreetMap community"

extendedDescription: 'Mapping in Bolivia? Have questions, want to connect with the community here? Join us at {Url}. All are welcome!'

### Languages spoken (optional)

"es"

### Country codes (optional)

"bo"

**Comment by bhousel** [comment]
done in 1739626
